Cheetah Software: ControlParameters Class Reference
ControlParameters Class Reference
#include <ControlParameters.h>
Public Member Functions
ControlParameters (const std::string &name)
bool isFullyInitialized ()
void initializeDouble (const std::string &name, double d)
void initializeFloat (const std::string &name, float f)
void initializeInteger (const std::string &name, s64 i)
void initializeVec3f (const std::string &name, Vec3< float > &v)
void initializeVec3d (const std::string &name, Vec3< double > &v)
void lockMutex ()
void unlockMutex ()
void writeToIniFile (const std::string &path)
void initializeFromIniFile (const std::string &path)
void initializeFromYamlFile (const std::string &path)
void defineAndInitializeFromYamlFile (const std::string &path)
void writeToYamlFile (const std::string &path)
std::string generateUnitializedList ()
Public Attributes
ControlParameterCollection collection
Protected Attributes
std::string _name
std::mutex _mutex
Detailed Description
Parent class for groups of parameters RobotParameters and SimulatorParameters inherit from this class. This will track if all parameters are initialized so you are sure that the robot has received all parameters before starting
Definition at line 481 of file ControlParameters.h.
Constructor & Destructor Documentation
ControlParameters()
ControlParameters::ControlParameters (const std::string & name) inline
Construct a control parameter group
Parameters
name : Each control parameter group must have a unique name so the ini files don't mixed up
Definition at line 488 of file ControlParameters.h.
 : collection(name), _name(name) {}
Member Function Documentation
defineAndInitializeFromYamlFile()
void ControlParameters::defineAndInitializeFromYamlFile (const std::string & path)
Add and initialize parameters from a YAML file
Definition at line 326 of file ControlParameters.cpp.
{
   ParamHandler paramHandler(path);
   if (!paramHandler.fileOpenedSuccessfully()) {
     printf(
         "[ERROR] Could not open yaml file %s : not initializing control "
         "parameters!\n",
         path.c_str());
     throw std::runtime_error("yaml file bad");
   }
   std::string name;
   if (!paramHandler.getString(YAML_COLLECTION_NAME_KEY, name)) {
     printf("[ERROR] YAML doesn't have a a collection name field named %s\n",
            YAML_COLLECTION_NAME_KEY);
     throw std::runtime_error("yaml file bad");
   }
   if (name != _name) {
     printf(
         "[ERROR] YAML file %s has collection name %s which cannot be used to "
         "initialize %s\n",
         path.c_str(), name.c_str(), _name.c_str());
     throw std::runtime_error("yaml file bad");
   }
   std::vector<std::string> keys = paramHandler.getKeys();
   for (auto& key : keys) {
     if (key == YAML_COLLECTION_NAME_KEY) continue;
     std::string valueString;
     paramHandler.getString(key, valueString);
     ControlParameterValueKind kind;
     if(valueString.empty()) {
       kind = ControlParameterValueKind::VEC3_DOUBLE;
     } else {
       kind = ControlParameterValueKind::DOUBLE;
     }
     ControlParameter* cp = new ControlParameter(key, kind);
     collection.addParameter(cp, key);
     switch (cp->_kind) {
       case ControlParameterValueKind::DOUBLE: {
         double d;
         assert(paramHandler.getValue(key, d));
         cp->initializeDouble(d);
       } break;
       case ControlParameterValueKind::FLOAT: {
         float f;
         assert(paramHandler.getValue(key, f));
         cp->initializeFloat(f);
       } break;
       case ControlParameterValueKind::S64: {
         s64 f;
         assert(paramHandler.getValue(key, f));
         cp->initializeInteger(f);
       } break;
       case ControlParameterValueKind::VEC3_DOUBLE: {
         std::vector<double> vv;
         assert(paramHandler.getVector(key, vv));
         assert(vv.size() == 3);
         Vec3<double> v(vv[0], vv[1], vv[2]);
         cp->initializeVec3d(v);
       } break;
       case ControlParameterValueKind::VEC3_FLOAT: {
         std::vector<float> vv;
         assert(paramHandler.getVector(key, vv));
         assert(vv.size() == 3);
         Vec3<float> v(vv[0], vv[1], vv[2]);
         cp->initializeVec3f(v);
       } break;
       default:
         throw std::runtime_error("can't read type " +
                                  std::to_string((u32)cp->_kind) +
                                  " from yaml file");
         break;
     }
   }
 }
References ControlParameter::_kind, _name, ControlParameterCollection::addParameter(), collection, DOUBLE, FLOAT, ControlParameter::initializeDouble(), ControlParameter::initializeFloat(), ControlParameter::initializeInteger(), ControlParameter::initializeVec3d(), ControlParameter::initializeVec3f(), S64, VEC3_DOUBLE, VEC3_FLOAT, and YAML_COLLECTION_NAME_KEY.
generateUnitializedList()
std::string ControlParameters::generateUnitializedList ()
Write a list of uninitialized parameters to a string
Definition at line 109 of file ControlParameters.cpp.
{
   std::string result;
   for (auto& kv : collection._map) {
     if (!kv.second->_set) {
       result += kv.second->_name + "    :\n";
     }
   }
   return result;
 }
References ControlParameterCollection::_map, and collection.
initializeDouble()
void ControlParameters::initializeDouble (const std::string & name, double d) inline
Directly initialize a given control parameter by name.
Parameters
name : name of parameter to initialize
d : double value to initialize with
Definition at line 500 of file ControlParameters.h.
{
     collection.lookup(name).initializeDouble(d);
   }
References collection, ControlParameter::initializeDouble(), and ControlParameterCollection::lookup().
initializeFloat()
void ControlParameters::initializeFloat (const std::string & name, float f) inline
Directly initialize a given control parameter by name.
Parameters
name : name of parameter to initialize
f : float value to initialize with
Definition at line 509 of file ControlParameters.h.
{
     collection.lookup(name).initializeFloat(f);
   }
References collection, ControlParameter::initializeFloat(), and ControlParameterCollection::lookup().
initializeFromIniFile()
void ControlParameters::initializeFromIniFile (const std::string & path)
Load values from an INI file
Parameters
path : the file name
Definition at line 242 of file ControlParameters.cpp.
{
   INIReader iniReader(path);
   if (iniReader.ParseError() < 0) {
     printf(
         "[ERROR] Could not open ini file %s : not initializing control "
         "parameters!\n",
         path.c_str());
     throw std::runtime_error("ini file bad");
   }
   std::set<std::string> sections = iniReader.GetSections();
   if (sections.size() != 1) {
     printf(
         "[ERROR] INI file %s had %ld sections (expected 1) : not initializing "
         "control parameters\n",
         path.c_str(), sections.size());
     throw std::runtime_error("ini file bad");
   }
   std::string sectionName = *(sections.begin());
   if (sectionName != _name) {
     printf(
         "[ERROR] INI file %s has section name %s, which cannot be used to "
         "initialize %s\n",
         path.c_str(), sectionName.c_str(), _name.c_str());
     throw std::runtime_error("ini file bad");
   }
   std::set<std::string> parameterNames = iniReader.GetFields(sectionName);
   for (auto& name : parameterNames) {
     ControlParameter& cp = collection.lookup(name);
     switch (cp._kind) {
       case ControlParameterValueKind::DOUBLE:
         cp.initializeDouble(iniReader.GetReal(sectionName, name, 0.));
         break;
       case ControlParameterValueKind::FLOAT:
         cp.initializeFloat((float)iniReader.GetReal(sectionName, name, 0.));
         break;
       case ControlParameterValueKind::S64:
         cp.initializeInteger(iniReader.GetInteger(sectionName, name, 0));
         break;
       default:
         throw std::runtime_error("can't read type " +
                                  std::to_string((u32)cp._kind) +
                                  " from ini file");
         break;
     }
   }
 }
References ControlParameter::_kind, _name, collection, DOUBLE, FLOAT, ControlParameter::initializeDouble(), ControlParameter::initializeFloat(), ControlParameter::initializeInteger(), ControlParameterCollection::lookup(), and S64.
initializeFromYamlFile()
void ControlParameters::initializeFromYamlFile (const std::string & path)
Set parameters from a YAML file
Parameters
path : the file name
Definition at line 415 of file ControlParameters.cpp.
{
   ParamHandler paramHandler(path);
   if (!paramHandler.fileOpenedSuccessfully()) {
     printf(
         "[ERROR] Could not open yaml file %s : not initializing control "
         "parameters!\n",
         path.c_str());
     throw std::runtime_error("yaml file bad");
   }
   std::string name;
   if (!paramHandler.getString(YAML_COLLECTION_NAME_KEY, name)) {
     printf("[ERROR] YAML doesn't have a a collection name field named %s\n",
            YAML_COLLECTION_NAME_KEY);
     throw std::runtime_error("yaml file bad");
   }
   if (name != _name) {
     printf(
         "[ERROR] YAML file %s has collection name %s which cannot be used to "
         "initialize %s\n",
         path.c_str(), name.c_str(), _name.c_str());
     throw std::runtime_error("yaml file bad");
   }
   std::vector<std::string> keys = paramHandler.getKeys();
   for (auto& key : keys) {
     if (key == YAML_COLLECTION_NAME_KEY) continue;
     ControlParameter& cp = collection.lookup(key);
     switch (cp._kind) {
       case ControlParameterValueKind::DOUBLE: {
         double d;
         assert(paramHandler.getValue(key, d));
         cp.initializeDouble(d);
       } break;
       case ControlParameterValueKind::FLOAT: {
         float f;
         assert(paramHandler.getValue(key, f));
         cp.initializeFloat(f);
       } break;
       case ControlParameterValueKind::S64: {
         s64 f;
         assert(paramHandler.getValue(key, f));
         cp.initializeInteger(f);
       } break;
       case ControlParameterValueKind::VEC3_DOUBLE: {
         std::vector<double> vv;
         assert(paramHandler.getVector(key, vv));
         assert(vv.size() == 3);
         Vec3<double> v(vv[0], vv[1], vv[2]);
         cp.initializeVec3d(v);
       } break;
       case ControlParameterValueKind::VEC3_FLOAT: {
         std::vector<float> vv;
         assert(paramHandler.getVector(key, vv));
         assert(vv.size() == 3);
         Vec3<float> v(vv[0], vv[1], vv[2]);
         cp.initializeVec3f(v);
       } break;
       default:
         throw std::runtime_error("can't read type " +
                                  std::to_string((u32)cp._kind) +
                                  " from yaml file");
         break;
     }
   }
 }
References ControlParameter::_kind, _name, collection, DOUBLE, FLOAT, ControlParameter::initializeDouble(), ControlParameter::initializeFloat(), ControlParameter::initializeInteger(), ControlParameter::initializeVec3d(), ControlParameter::initializeVec3f(), ControlParameterCollection::lookup(), S64, VEC3_DOUBLE, VEC3_FLOAT, and YAML_COLLECTION_NAME_KEY.
initializeInteger()
void ControlParameters::initializeInteger (const std::string & name, s64 i) inline
Directly initialize a given control parameter by name.
Parameters
name : name of parameter to initialize
i : s64 value to initialize with
Definition at line 518 of file ControlParameters.h.
{
     collection.lookup(name).initializeInteger(i);
   }
References collection, ControlParameter::initializeInteger(), and ControlParameterCollection::lookup().
initializeVec3d()
void ControlParameters::initializeVec3d (const std::string & name, Vec3< double > & v) inline
Directly initialize a given control parameter by name.
Parameters
name : name of parameter to initialize
v : list of 3 double value to initialize with
Definition at line 536 of file ControlParameters.h.
{
     collection.lookup(name).initializeVec3d(v);
   }
References collection, ControlParameter::initializeVec3d(), and ControlParameterCollection::lookup().
initializeVec3f()
void ControlParameters::initializeVec3f (const std::string & name, Vec3< float > & v) inline
Directly initialize a given control parameter by name.
Parameters
name : name of parameter to initialize
v : list of 3 floats value to initialize with
Definition at line 527 of file ControlParameters.h.
{
     collection.lookup(name).initializeVec3f(v);
   }
References collection, ControlParameter::initializeVec3f(), and ControlParameterCollection::lookup().
isFullyInitialized()
bool ControlParameters::isFullyInitialized () inline
If true, all parameters have been initialized in one way or another
Definition at line 493 of file ControlParameters.h.
 { return collection.checkIfAllSet(); }
References ControlParameterCollection::checkIfAllSet(), and collection.
lockMutex()
void ControlParameters::lockMutex () inline
Lock the access mutex. Control parameters are shared between UI, LCM, simulator, and robot threads
Definition at line 543 of file ControlParameters.h.
 { _mutex.lock(); }
References _mutex.
unlockMutex()
void ControlParameters::unlockMutex () inline
Unlock the access mutex. Control parameters are shared between UI, LCM, simulator, and robot threads
Definition at line 548 of file ControlParameters.h.
 { _mutex.unlock(); }
References _mutex.
writeToIniFile()
void ControlParameters::writeToIniFile (const std::string & path)
Write all parameters and values to an INI file
Parameters
path : the file name
Definition at line 226 of file ControlParameters.cpp.
{
   writeStringToFile(path, collection.printToIniString());
 }
References collection, ControlParameterCollection::printToIniString(), and writeStringToFile().
writeToYamlFile()
void ControlParameters::writeToYamlFile (const std::string & path)
Write all parameters and values to a YAML file
Parameters
path : the file name
Definition at line 234 of file ControlParameters.cpp.
{
   writeStringToFile(path, collection.printToYamlString());
 }
References collection, ControlParameterCollection::printToYamlString(), and writeStringToFile().
Member Data Documentation
_mutex
std::mutex ControlParameters::_mutex protected
Definition at line 563 of file ControlParameters.h.
_name
std::string ControlParameters::_name protected
Definition at line 562 of file ControlParameters.h.
collection
ControlParameterCollection ControlParameters::collection
Definition at line 559 of file ControlParameters.h.
The documentation for this class was generated from the following files:
ControlParameters.h
ControlParameters.cpp