Cheetah Software: SimControlPanel Class Reference
SimControlPanel Class Reference
#include <SimControlPanel.h>
Public Slots
void update_ui ()
void errorCallback (std::string errorMessage)
Public Member Functions
SimControlPanel (QWidget *parent=nullptr)
~SimControlPanel ()
Private Slots
void on_startButton_clicked ()
void on_stopButton_clicked ()
void on_joystickButton_clicked ()
void on_driverButton_clicked ()
void on_simulatorTable_cellChanged (int row, int column)
void on_saveSimulatorButton_clicked ()
void on_loadSimulatorButton_clicked ()
void on_robotTable_cellChanged (int row, int column)
void on_saveRobotButton_clicked ()
void on_loadRobotButton_clicked ()
void on_goHomeButton_clicked ()
void on_kickButton_clicked ()
void on_userControlTable_cellChanged (int row, int column)
void on_saveUserButton_clicked ()
void on_loadUserButton_clicked ()
void on_setTerrainButton_clicked ()
void on_hide_floor_checkbox_toggled (bool x)
void on_hide_robot_checkbox_toggled (bool x)
void updateTerrainLabel ()
void loadSimulationParameters (SimulatorControlParameters &params)
void loadRobotParameters (RobotControlParameters &params)
void loadUserParameters (ControlParameters &params)
Private Member Functions
std::string getDefaultUserParameterFileName ()
void updateUiEnable ()
bool isStopped ()
bool isError ()
bool isRunning ()
void handleHeightmapLCM (const lcm::ReceiveBuffer *rbuf, const std::string &chan, const heightmap_t *msg)
void heightmapLCMThread ()
void handlePointsLCM (const lcm::ReceiveBuffer *rbuf, const std::string &chan, const rs_pointcloud_t *msg)
void pointsLCMThread ()
void handleIndexmapLCM (const lcm::ReceiveBuffer *rbuf, const std::string &chan, const traversability_map_t *msg)
void indexmapLCMThread ()
void handleObstacleLCM (const lcm::ReceiveBuffer *rbuf, const std::string &chan, const obstacle_visual_t *msg)
void handleVelocityCMDLCM (const lcm::ReceiveBuffer *rbuf, const std::string &chan, const velocity_visual_t *msg)
void ctrlVisionLCMThread ()
void handleSpiDebug (const lcm::ReceiveBuffer *rbuf, const std::string &chan, const leg_control_data_lcmt *msg)
Private Attributes
std::thread _simThread
SimulationWindowState _state = SimulationWindowState::STOPPED
Ui::SimControlPanel * ui
Simulation * _simulation = nullptr
PeriodicTaskManager * _interfaceTaskManager = nullptr
RobotInterface * _robotInterface = nullptr
Graphics3D * _graphicsWindow = nullptr
SimulatorControlParameters _parameters
ControlParameters _userParameters
bool _simulationMode = false
bool _firstStart = true
bool _ignoreTableCallbacks = false
bool _loadedUserSettings = false
std::string _terrainFileName
lcm::LCM _heightmapLCM
lcm::LCM _pointsLCM
lcm::LCM _indexmapLCM
lcm::LCM _ctrlVisionLCM
lcm::LCM _miniCheetahDebugLCM
std::thread _pointsLCMThread
std::thread _heightmapLCMThread
std::thread _indexmapLCMThread
std::thread _ctrlVisionLCMThread
std::thread _miniCheetahDebugLCMThread
MiniCheetahDebug _mcDebugWindow
Detailed Description
Definition at line 38 of file SimControlPanel.h.
Constructor & Destructor Documentation
SimControlPanel()
SimControlPanel::SimControlPanel (QWidget * parent = nullptr) explicit
Init sim window
Definition at line 73 of file SimControlPanel.cpp.
     : QMainWindow(parent),
       ui(new Ui::SimControlPanel),
       _userParameters("user-parameters"),
       _terrainFileName(getConfigDirectoryPath() + DEFAULT_TERRAIN_FILE),
       _heightmapLCM(getLcmUrl(255)),
       _pointsLCM(getLcmUrl(255)),
       _indexmapLCM(getLcmUrl(255)),
       _ctrlVisionLCM(getLcmUrl(255)),
       _miniCheetahDebugLCM(getLcmUrl(255))
 {
   ui->setupUi(this); // QT setup
   updateUiEnable();  // enable/disable buttons as needed.
   updateTerrainLabel(); // display name of loaded terrain file
   // attempt to load default user settings.
   _loadedUserSettings = true;
   try {
     _userParameters.defineAndInitializeFromYamlFile(getConfigDirectoryPath() + getDefaultUserParameterFileName());
   } catch (std::runtime_error& ex) {
     _loadedUserSettings = false;
   }
   if(!_loadedUserSettings) {
     printf("[SimControlPanel] Failed to load default user settings!\n");
     throw std::runtime_error("Failed to load default user settings!");
   } else {
     // display user settings in qtable if we loaded successfully
     loadUserParameters(_userParameters);
   }
   // load simulator parameters
   printf("[SimControlPanel] Init simulator parameters...\n");
   _parameters.initializeFromYamlFile(getConfigDirectoryPath() +
                                      SIMULATOR_DEFAULT_PARAMETERS);
   if (!_parameters.isFullyInitialized()) {
     printf(
         "[ERROR] Simulator parameters are not fully initialized.  You forgot: "
         "\n%s\n",
         _parameters.generateUnitializedList().c_str());
     throw std::runtime_error("simulator not initialized");
   } else {
     printf("\tsim parameters are all good\n");
   }
   loadSimulationParameters(_parameters);
   _pointsLCM.subscribe("cf_pointcloud", &SimControlPanel::handlePointsLCM, this);
   _pointsLCMThread = std::thread(&SimControlPanel::pointsLCMThread, this);
   _heightmapLCM.subscribe("local_heightmap", &SimControlPanel::handleHeightmapLCM, this);
   _heightmapLCMThread = std::thread(&SimControlPanel::heightmapLCMThread, this);
   _indexmapLCM.subscribe("traversability", &SimControlPanel::handleIndexmapLCM, this);
   _indexmapLCMThread = std::thread(&SimControlPanel::indexmapLCMThread, this);
   _ctrlVisionLCM.subscribe("velocity_cmd", &SimControlPanel::handleVelocityCMDLCM, this);
   _ctrlVisionLCM.subscribe("obstacle_visual", &SimControlPanel::handleObstacleLCM, this);
   _ctrlVisionLCMThread = std::thread(&SimControlPanel::ctrlVisionLCMThread, this);
   // subscribe mc debug
   _miniCheetahDebugLCM.subscribe("leg_control_data", &SimControlPanel::handleSpiDebug, this);
   _miniCheetahDebugLCMThread = std::thread([&](){
    for(;;)
      _miniCheetahDebugLCM.handle();
   });
 }
References _ctrlVisionLCM, _ctrlVisionLCMThread, _heightmapLCM, _heightmapLCMThread, _indexmapLCM, _indexmapLCMThread, _loadedUserSettings, _miniCheetahDebugLCM, _miniCheetahDebugLCMThread, _parameters, _pointsLCM, _pointsLCMThread, _userParameters, ctrlVisionLCMThread(), ControlParameters::defineAndInitializeFromYamlFile(), ControlParameters::generateUnitializedList(), getConfigDirectoryPath(), getDefaultUserParameterFileName(), handleHeightmapLCM(), handleIndexmapLCM(), handleObstacleLCM(), handlePointsLCM(), handleSpiDebug(), handleVelocityCMDLCM(), heightmapLCMThread(), indexmapLCMThread(), ControlParameters::initializeFromYamlFile(), ControlParameters::isFullyInitialized(), loadSimulationParameters(), loadUserParameters(), pointsLCMThread(), SIMULATOR_DEFAULT_PARAMETERS, ui, updateTerrainLabel(), and updateUiEnable().
~SimControlPanel()
SimControlPanel::~SimControlPanel ()
Definition at line 274 of file SimControlPanel.cpp.
{
   delete _simulation;
   delete _interfaceTaskManager;
   delete _robotInterface;
   delete _graphicsWindow;
   delete ui;
 }
References _graphicsWindow, _interfaceTaskManager, _robotInterface, _simulation, and ui.
Member Function Documentation
ctrlVisionLCMThread()
void SimControlPanel::ctrlVisionLCMThread () inline private
Definition at line 153 of file SimControlPanel.h.
 { while(true){ _ctrlVisionLCM.handle();  } }
References _ctrlVisionLCM.
errorCallback
void SimControlPanel::errorCallback (std::string errorMessage) slot
Simulation error
Definition at line 336 of file SimControlPanel.cpp.
{
   _state = SimulationWindowState::ERROR; // go to error state
   updateUiEnable(); // update UI
   createErrorMessage("Simulation Error\n" + errorMessage); // display error dialog
 }
References _state, createErrorMessage(), ERROR, and updateUiEnable().
getDefaultUserParameterFileName()
std::string SimControlPanel::getDefaultUserParameterFileName () private
Definition at line 45 of file SimControlPanel.cpp.
{
   std::string path = getConfigDirectoryPath() + DEFAULT_USER_FILE;
   ParamHandler paramHandler(path);
   if(!paramHandler.fileOpenedSuccessfully()) {
     throw std::runtime_error("Could not open yaml file for default user parameter file: " + path);
   }
   std::string collectionName;
   if(!paramHandler.getString("__collection-name__", collectionName)) {
     throw std::runtime_error("Could not find __collection-name__ parameter in default user parameter file");
   }
   if(collectionName != "user-parameter-file") {
     throw std::runtime_error("default user parameter file has the wrong collection name, should be user-parameter-file");
   }
   std::string fileName;
   if(!paramHandler.getString("file_name", fileName)) {
     throw std::runtime_error("default user parameter file does not have a parameter named file_name");
   }
   return fileName;
 }
References DEFAULT_USER_FILE, and getConfigDirectoryPath().
handleHeightmapLCM()
void SimControlPanel::handleHeightmapLCM (const lcm::ReceiveBuffer * rbuf, const std::string & chan, const heightmap_t * msg) private
Definition at line 215 of file SimControlPanel.cpp.
{
   (void)rbuf;
   (void)chan;
   if(_graphicsWindow){
     for(size_t i(0); i<_graphicsWindow->x_size; ++i){
       for(size_t j(0); j<_graphicsWindow->y_size; ++j){
         _graphicsWindow->_map(i,j) = msg->map[i][j];
       }
     }
     _graphicsWindow->_pos[0] = msg->robot_loc[0];
     _graphicsWindow->_pos[1] = msg->robot_loc[1];
     _graphicsWindow->_pos[2] = msg->robot_loc[2];
     _graphicsWindow->_heightmap_data_update = true;
   }
 }
References _graphicsWindow, Graphics3D::_heightmap_data_update, Graphics3D::_map, Graphics3D::_pos, Graphics3D::x_size, and Graphics3D::y_size.
handleIndexmapLCM()
void SimControlPanel::handleIndexmapLCM (const lcm::ReceiveBuffer * rbuf, const std::string & chan, const traversability_map_t * msg) private
Definition at line 198 of file SimControlPanel.cpp.
{
   (void)rbuf;
   (void)chan;
   if(_graphicsWindow){
     for(size_t i(0); i<_graphicsWindow->x_size; ++i){
       for(size_t j(0); j<_graphicsWindow->y_size; ++j){
         _graphicsWindow->_idx_map(i,j) = msg->map[i][j];
       }
     }
     _graphicsWindow->_indexmap_data_update = true;
   }
 }
References _graphicsWindow, Graphics3D::_idx_map, Graphics3D::_indexmap_data_update, Graphics3D::x_size, and Graphics3D::y_size.
handleObstacleLCM()
void SimControlPanel::handleObstacleLCM (const lcm::ReceiveBuffer * rbuf, const std::string & chan, const obstacle_visual_t * msg) private
Definition at line 158 of file SimControlPanel.cpp.
{
   (void)rbuf;
   (void)chan;
   if(_graphicsWindow){
     _graphicsWindow->_obs_list.clear();
     Vec3<double> obs_loc;
     for(int i(0); i<msg->num_obs; ++i){
       obs_loc[0] = msg->location[i][0];
       obs_loc[1] = msg->location[i][1];
       obs_loc[2] = msg->location[i][2];
       _graphicsWindow->_obs_list.push_back(obs_loc);
     }
     _graphicsWindow->_obs_sigma = msg->sigma;
     _graphicsWindow->_obs_height = msg->height;
     _graphicsWindow->_obstacle_update = true;
     //printf("%f, %f\n", _graphicsWindow->_obs_list[0][0], _graphicsWindow->_obs_list[0][1]);
   }
 }
References _graphicsWindow, Graphics3D::_obs_height, Graphics3D::_obs_list, Graphics3D::_obs_sigma, and Graphics3D::_obstacle_update.
handlePointsLCM()
void SimControlPanel::handlePointsLCM (const lcm::ReceiveBuffer * rbuf, const std::string & chan, const rs_pointcloud_t * msg) private
Definition at line 182 of file SimControlPanel.cpp.
{
   (void)rbuf;
   (void)chan;
   if(_graphicsWindow){
     for(size_t i(0); i<_graphicsWindow->_num_points; ++i){
       for(size_t j(0); j<3; ++j){
         _graphicsWindow->_points[i][j] = msg->pointlist[i][j];
       }
     }
     _graphicsWindow->_pointcloud_data_update = true;
   }
 }
References _graphicsWindow, Graphics3D::_num_points, Graphics3D::_pointcloud_data_update, and Graphics3D::_points.
handleSpiDebug()
void SimControlPanel::handleSpiDebug (const lcm::ReceiveBuffer * rbuf, const std::string & chan, const leg_control_data_lcmt * msg) private
Definition at line 235 of file SimControlPanel.cpp.
{
   (void)rbuf;
   (void)chan;
   MiniCheetahDebugData ddata;
   u32 idx = 0;
   for(u32 leg = 0; leg < 4; leg++) {
     for(u32 joint = 0; joint < 3; joint++) {
       ddata.p[leg][joint] = msg->q[idx];
       ddata.v[leg][joint] = msg->qd[idx];
       idx++;
     }
   }
   if(_mcDebugWindow.setDebugData(ddata)) {
     MiniCheetahDebugCommand cmd;
     _mcDebugWindow.getDebugCommand(cmd);
     leg_control_command_lcmt lcm_cmd;
     memset(&lcm_cmd, 0, sizeof(leg_control_command_lcmt));
     idx = 0;
     for(u32 leg = 0; leg < 4; leg++) {
       for(u32 joint = 0; joint < 3; joint++) {
         if(cmd.enable[leg][joint]) {
           lcm_cmd.q_des[idx] = cmd.qd[leg][joint];
           lcm_cmd.kp_joint[idx] = cmd.kp[leg][joint];
           lcm_cmd.kd_joint[idx] = cmd.kd[leg][joint];
         }
         idx++;
       }
     }
     _miniCheetahDebugLCM.publish("spi_debug_cmd", &lcm_cmd);
   }
 }
References _mcDebugWindow, _miniCheetahDebugLCM, MiniCheetahDebugCommand::enable, MiniCheetahDebug::getDebugCommand(), MiniCheetahDebugCommand::kd, MiniCheetahDebugCommand::kp, MiniCheetahDebugData::p, MiniCheetahDebugCommand::qd, MiniCheetahDebug::setDebugData(), and MiniCheetahDebugData::v.
handleVelocityCMDLCM()
void SimControlPanel::handleVelocityCMDLCM (const lcm::ReceiveBuffer * rbuf, const std::string & chan, const velocity_visual_t * msg) private
Definition at line 143 of file SimControlPanel.cpp.
{
   (void)rbuf;
   (void)chan;
   if(_graphicsWindow){
     for(size_t i(0); i<3; ++i){
       _graphicsWindow->_vel_cmd_dir[i] = msg->vel_cmd[i];
       _graphicsWindow->_vel_cmd_pos[i] = msg->base_position[i];
     }
     _graphicsWindow->_vel_cmd_update = true;
   }
 }
References _graphicsWindow, Graphics3D::_vel_cmd_dir, Graphics3D::_vel_cmd_pos, and Graphics3D::_vel_cmd_update.
heightmapLCMThread()
void SimControlPanel::heightmapLCMThread () inline private
Definition at line 139 of file SimControlPanel.h.
 { while (true) { _heightmapLCM.handle(); } }
References _heightmapLCM.
indexmapLCMThread()
void SimControlPanel::indexmapLCMThread () inline private
Definition at line 147 of file SimControlPanel.h.
 { while (true) { _indexmapLCM.handle(); } }
References _indexmapLCM.
isError()
bool SimControlPanel::isError () inline private
Definition at line 111 of file SimControlPanel.h.
                  {
     return _state == SimulationWindowState::ERROR;
   }
References _state, and ERROR.
isRunning()
bool SimControlPanel::isRunning () inline private
Definition at line 115 of file SimControlPanel.h.
                    {
     return _state == SimulationWindowState::RUNNING;
   }
References _state, and RUNNING.
isStopped()
bool SimControlPanel::isStopped () inline private
Definition at line 107 of file SimControlPanel.h.
                    {
     return _state == SimulationWindowState::STOPPED;
   }
References _state, and STOPPED.
loadRobotParameters
void SimControlPanel::loadRobotParameters (RobotControlParameters & params) private slot
Populate the robot qtable parameters
Definition at line 482 of file SimControlPanel.cpp.
{
   _ignoreTableCallbacks = true;
   updateQtableWithParameters(params, *ui->robotTable);
   _ignoreTableCallbacks = false;
 }
References _ignoreTableCallbacks, ui, and updateQtableWithParameters().
loadSimulationParameters
void SimControlPanel::loadSimulationParameters (SimulatorControlParameters & params) private slot
Populate the simulator qtable parameters
Definition at line 472 of file SimControlPanel.cpp.
{
   _ignoreTableCallbacks = true;
   updateQtableWithParameters(params, *ui->simulatorTable);
   _ignoreTableCallbacks = false;
 }
References _ignoreTableCallbacks, ui, and updateQtableWithParameters().
loadUserParameters
void SimControlPanel::loadUserParameters (ControlParameters & params) private slot
Populate the robot qtable parameters
Definition at line 491 of file SimControlPanel.cpp.
{
   _ignoreTableCallbacks = true;
   updateQtableWithParameters(params, *ui->userControlTable);
   _ignoreTableCallbacks = false;
 }
References _ignoreTableCallbacks, ui, and updateQtableWithParameters().
on_driverButton_clicked
void SimControlPanel::on_driverButton_clicked () private slot
Definition at line 509 of file SimControlPanel.cpp.
{
   _mcDebugWindow.show();
 }
References _mcDebugWindow.
on_goHomeButton_clicked
void SimControlPanel::on_goHomeButton_clicked () private slot
Definition at line 847 of file SimControlPanel.cpp.
{
   printf("go home\n");
   FBModelState<double> homeState;
   homeState.bodyOrientation << 1, 0, 0, 0;
   homeState.bodyPosition = Vec3<double>(0, 0, 0.4);
   homeState.bodyVelocity = SVec<double>::Zero();
   homeState.q = DVec<double>(12);
   homeState.q << -0.05, -0.8, 1.7, 0.05, -0.8, 1.7, -0.05, -0.8, 1.7, 0.05, -0.8, 1.7;
   homeState.qd = homeState.q;
   _simulation->setRobotState(homeState);
 }
References _simulation, FBModelState< T >::bodyOrientation, FBModelState< T >::bodyPosition, FBModelState< T >::bodyVelocity, FBModelState< T >::q, FBModelState< T >::qd, and Simulation::setRobotState().
on_hide_floor_checkbox_toggled
void SimControlPanel::on_hide_floor_checkbox_toggled (bool x) inline private slot
Definition at line 85 of file SimControlPanel.h.
{
     if(_graphicsWindow) {
       _graphicsWindow->setHideFloor(x);
     }
   }
References _graphicsWindow, and Graphics3D::setHideFloor().
on_hide_robot_checkbox_toggled
void SimControlPanel::on_hide_robot_checkbox_toggled (bool x) inline private slot
Definition at line 91 of file SimControlPanel.h.
{
     if(_graphicsWindow) {
       _graphicsWindow->setHideRobot(x);
     }
   }
References _graphicsWindow, and Graphics3D::setHideRobot().
on_joystickButton_clicked
void SimControlPanel::on_joystickButton_clicked () private slot
Attempt to reset the joystick if a new one is connected
Definition at line 500 of file SimControlPanel.cpp.
{
   if(isRunning()) {
     _graphicsWindow->resetGameController();
     JoystickTestWindow* window = new JoystickTestWindow(_graphicsWindow->getGameController());
     window->exec();
     delete window;
   }
 }
References _graphicsWindow, Graphics3D::getGameController(), isRunning(), and Graphics3D::resetGameController().
on_kickButton_clicked
void SimControlPanel::on_kickButton_clicked () private slot
Definition at line 860 of file SimControlPanel.cpp.
{
   // velocity of the floating base:
   SVec<double> kickVelocity;
   kickVelocity << ui->kickAngularX->text().toDouble(),
       ui->kickAngularY->text().toDouble(), ui->kickAngularZ->text().toDouble(),
       ui->kickLinearX->text().toDouble(), ui->kickLinearY->text().toDouble(),
       ui->kickLinearZ->text().toDouble();
   FBModelState<double> state = _simulation->getRobotState();
   state.bodyVelocity += kickVelocity;
   _simulation->setRobotState(state);
 }
References _simulation, FBModelState< T >::bodyVelocity, Simulation::getRobotState(), Simulation::setRobotState(), and ui.
on_loadRobotButton_clicked
void SimControlPanel::on_loadRobotButton_clicked () private slot
Definition at line 677 of file SimControlPanel.cpp.
{
   QString fileName = QFileDialog::getOpenFileName(
       nullptr, ("Load Quadruped Table Values"), "../config", "All Files (*)");
   if (fileName == nullptr || fileName == "") {
     createErrorMessage("File name is invalid");
     return;
   }
   if (_simulationMode) {
     _simulation->getRobotParams().lockMutex();
     _simulation->getRobotParams().collection.clearAllSet();
     _simulation->getRobotParams().initializeFromYamlFile(
         fileName.toStdString());
     if (!_simulation->getRobotParams().collection.checkIfAllSet()) {
       printf(
           "new settings file %s doesn't contain the following robot "
           "parameters:\n%s\n",
           fileName.toStdString().c_str(),
           _simulation->getRobotParams().generateUnitializedList().c_str());
       throw std::runtime_error("bad new settings file");
     }
     loadRobotParameters(_simulation->getRobotParams());
     if (_simulation->isRobotConnected()) {
       for (auto& kv : _simulation->getRobotParams().collection._map) {
         _simulation->sendControlParameter(
             kv.first, kv.second->get(kv.second->_kind), kv.second->_kind, false);
       }
     }
     _simulation->getRobotParams().unlockMutex();
   } else {
     _robotInterface->getParams().lockMutex();
     _robotInterface->getParams().collection.clearAllSet();
     _robotInterface->getParams().initializeFromYamlFile(fileName.toStdString());
     if (!_robotInterface->getParams().collection.checkIfAllSet()) {
       printf(
           "new settings file %s doesn't contain the following robot "
           "parameters:\n%s\n",
           fileName.toStdString().c_str(),
           _robotInterface->getParams().generateUnitializedList().c_str());
       throw std::runtime_error("bad new settings file");
     }
     loadRobotParameters(_robotInterface->getParams());
     for (auto& kv : _robotInterface->getParams().collection._map) {
       _robotInterface->sendControlParameter(
           kv.first, kv.second->get(kv.second->_kind), kv.second->_kind, false);
     }
     _robotInterface->getParams().unlockMutex();
   }
 }
References ControlParameterCollection::_map, _robotInterface, _simulation, _simulationMode, ControlParameterCollection::checkIfAllSet(), ControlParameterCollection::clearAllSet(), ControlParameters::collection, createErrorMessage(), ControlParameters::generateUnitializedList(), RobotInterface::getParams(), Simulation::getRobotParams(), ControlParameters::initializeFromYamlFile(), Simulation::isRobotConnected(), loadRobotParameters(), ControlParameters::lockMutex(), RobotInterface::sendControlParameter(), Simulation::sendControlParameter(), and ControlParameters::unlockMutex().
on_loadSimulatorButton_clicked
void SimControlPanel::on_loadSimulatorButton_clicked () private slot
Load simulation config from file
Definition at line 589 of file SimControlPanel.cpp.
{
   QString fileName = QFileDialog::getOpenFileName(
       nullptr, ("Load Simulator Table Values"), "../config", "All Files (*)");
   if (fileName == nullptr || fileName == "") {
     createErrorMessage("File name is invalid");
     return;
   };
   _parameters.collection.clearAllSet();
   _parameters.initializeFromYamlFile(fileName.toStdString());
   if (!_parameters.collection.checkIfAllSet()) {
     printf(
         "new settings file %s doesn't contain the following simulator "
         "parameters:\n%s\n",
         fileName.toStdString().c_str(),
         _parameters.generateUnitializedList().c_str());
     throw std::runtime_error("bad new settings file");
   }
   loadSimulationParameters(_parameters);
   _parameters.unlockMutex();
 }
References _parameters, ControlParameterCollection::checkIfAllSet(), ControlParameterCollection::clearAllSet(), ControlParameters::collection, createErrorMessage(), ControlParameters::generateUnitializedList(), ControlParameters::initializeFromYamlFile(), loadSimulationParameters(), and ControlParameters::unlockMutex().
on_loadUserButton_clicked
void SimControlPanel::on_loadUserButton_clicked () private slot
Definition at line 803 of file SimControlPanel.cpp.
{
   QString fileName = QFileDialog::getOpenFileName(
       nullptr, ("Load User Table Values"), "../config", "All Files (*)");
   if (fileName == nullptr || fileName == "") {
     createErrorMessage("File name is invalid");
     return;
   }
   _userParameters.lockMutex();
   _userParameters.collection.deleteAll();
   _userParameters.defineAndInitializeFromYamlFile(
       fileName.toStdString());
   loadUserParameters(_userParameters);
   _userParameters.unlockMutex();
   _loadedUserSettings = true;
   if(isRunning() || isError()) {
     if (_simulationMode) {
       if (_simulation && _simulation->isRobotConnected()) {
         for (auto& kv : _userParameters.collection._map) {
           _simulation->sendControlParameter(
               kv.first, kv.second->get(kv.second->_kind), kv.second->_kind, true);
         }
       }
     } else {
     for (auto& kv : _userParameters.collection._map) {
       _robotInterface->sendControlParameter(
           kv.first, kv.second->get(kv.second->_kind), kv.second->_kind, true);
     }
     }
   }
 }
References _loadedUserSettings, ControlParameterCollection::_map, _robotInterface, _simulation, _simulationMode, _userParameters, ControlParameters::collection, createErrorMessage(), ControlParameters::defineAndInitializeFromYamlFile(), ControlParameterCollection::deleteAll(), isError(), Simulation::isRobotConnected(), isRunning(), loadUserParameters(), ControlParameters::lockMutex(), RobotInterface::sendControlParameter(), Simulation::sendControlParameter(), and ControlParameters::unlockMutex().
on_robotTable_cellChanged
void SimControlPanel::on_robotTable_cellChanged (int row, int column) private slot
Definition at line 610 of file SimControlPanel.cpp.
{
   if (_ignoreTableCallbacks) return;
   if (column != 1) {
     return;
   }
   auto cell = ui->robotTable->item(row, 0);
   std::string cellName = cell->text().toStdString();
   if (cellName == "") {
     return;
   }
   auto& parameter = (_simulationMode ? _simulation->getRobotParams()
                                      : _robotInterface->getParams())
                         .collection.lookup(cellName);
   ControlParameterValueKind kind = parameter._kind;
   ControlParameterValue oldValue = parameter.get(kind);
   bool success = true;
   try {
     parameter.setFromString(ui->robotTable->item(row, 1)->text().toStdString());
   } catch (std::exception& e) {
     success = false;
   }
   if (!success) {
     printf("[ERROR] invalid data, restoring old data!\n");
     parameter.set(oldValue, kind);
     assert(!_ignoreTableCallbacks);
     _ignoreTableCallbacks = true;
     ui->robotTable->item(row, 1)->setText(
         QString(parameter
                     .toString()
                     .c_str()));
     _ignoreTableCallbacks = false;
   } else {
     if (_simulationMode) {
       if (_simulation->isRobotConnected()) {
         _simulation->sendControlParameter(
             cellName, parameter.get(parameter._kind), parameter._kind, false);
       }
       _ignoreTableCallbacks = true;
       ui->robotTable->item(row, 1)->setText(
           QString(parameter.toString().c_str()));
       _ignoreTableCallbacks = false;
     } else {
       _robotInterface->sendControlParameter(
           cellName, parameter.get(parameter._kind), parameter._kind, false);
     }
   }
 }
References _ignoreTableCallbacks, _robotInterface, _simulation, _simulationMode, RobotInterface::getParams(), Simulation::getRobotParams(), Simulation::isRobotConnected(), RobotInterface::sendControlParameter(), Simulation::sendControlParameter(), and ui.
on_saveRobotButton_clicked
void SimControlPanel::on_saveRobotButton_clicked () private slot
Definition at line 667 of file SimControlPanel.cpp.
{
   QString fileName = QFileDialog::getSaveFileName(
       nullptr, ("Save Robot Table Values"), "../config", "All Files (*)");
   if (fileName == nullptr || fileName == "") {
     createErrorMessage("File name is invalid");
     return;
   }
   _simulation->getRobotParams().writeToYamlFile(fileName.toStdString());
 }
References _simulation, createErrorMessage(), Simulation::getRobotParams(), and ControlParameters::writeToYamlFile().
on_saveSimulatorButton_clicked
void SimControlPanel::on_saveSimulatorButton_clicked () private slot
Save simulation config to file
Definition at line 573 of file SimControlPanel.cpp.
{
   QString fileName = QFileDialog::getSaveFileName(
       nullptr, ("Save Simulator Table Values"), "../config", "All Files (*)");
   if (fileName == nullptr || fileName == "") {
     createErrorMessage("File name is invalid");
     return;
   }
   _parameters.lockMutex();
   _parameters.writeToYamlFile(fileName.toStdString());
   _parameters.unlockMutex();
 }
References _parameters, createErrorMessage(), ControlParameters::lockMutex(), ControlParameters::unlockMutex(), and ControlParameters::writeToYamlFile().
on_saveUserButton_clicked
void SimControlPanel::on_saveUserButton_clicked () private slot
Definition at line 837 of file SimControlPanel.cpp.
{
   QString fileName = QFileDialog::getSaveFileName(
       nullptr, ("Save User Table Values"), "../config", "All Files (*)");
   if (fileName == nullptr || fileName == "") {
     createErrorMessage("File name is invalid");
     return;
   }
   _userParameters.writeToYamlFile(fileName.toStdString());
 }
References _userParameters, createErrorMessage(), and ControlParameters::writeToYamlFile().
on_setTerrainButton_clicked
void SimControlPanel::on_setTerrainButton_clicked () private slot
Definition at line 730 of file SimControlPanel.cpp.
{
   QString fileName = QFileDialog::getOpenFileName(
       nullptr, ("Load Terrain Definition"), "../config", "All Files (*)");
   if (fileName == nullptr || fileName == "") {
     createErrorMessage("File name is invalid");
     return;
   }
   _terrainFileName = fileName.toStdString();
   updateTerrainLabel();
 }
References _terrainFileName, createErrorMessage(), and updateTerrainLabel().
on_simulatorTable_cellChanged
void SimControlPanel::on_simulatorTable_cellChanged (int row, int column) private slot
Respond to a change in the simulator table.
Definition at line 516 of file SimControlPanel.cpp.
{
   if (_ignoreTableCallbacks) return;
   // we only allow values to change, which are in column 1
   if (column != 1) {
     return;
   }
   // get the name of the parameter....
   auto cell = ui->simulatorTable->item(row, 0);
   std::string cellName = cell->text().toStdString();
   if (cellName == "") {
     return;
   }
   // get the parameters
   auto& parameter = _parameters.collection.lookup(cellName);
   ControlParameterValueKind kind = parameter._kind;
   ControlParameterValue oldValue = parameter.get(kind);
   bool success = true;
   // attempt to set, based on string.
   try {
     parameter.setFromString(
         ui->simulatorTable->item(row, 1)->text().toStdString());
   } catch (std::exception& e) {
     success = false;
   }
   // if it fails (bad user input string), restore to the old value
   if (!success) {
     printf("[ERROR] invalid data, restoring old data!\n");
     // set parameter value
     parameter.set(oldValue, kind);
     assert(!_ignoreTableCallbacks);
     // manually fix the table
     _ignoreTableCallbacks = true;
     ui->simulatorTable->item(row, 1)->setText(
         QString(_parameters.collection.lookup(cellName).toString().c_str()));
     _ignoreTableCallbacks = false;
   } else {
     // this update "rewrites" the value in the table.  If it's an integer, it kills any
     // decimal.  If it's a float, it puts in scientific notation if needed.
     _ignoreTableCallbacks = true;
     ui->simulatorTable->item(row, 1)->setText(
         QString(parameter.toString().c_str()));
     _ignoreTableCallbacks = false;
   }
 }
References _ignoreTableCallbacks, ControlParameter::_kind, _parameters, ControlParameters::collection, ControlParameterCollection::lookup(), ControlParameter::toString(), and ui.
on_startButton_clicked
void SimControlPanel::on_startButton_clicked () private slot
Start a simulation/robot run
Definition at line 345 of file SimControlPanel.cpp.
{
   // get robot type
   RobotType robotType;
   if (ui->cheetah3Button->isChecked()) {
     robotType = RobotType::CHEETAH_3;
   } else if (ui->miniCheetahButton->isChecked()) {
     robotType = RobotType::MINI_CHEETAH;
   } else {
     createErrorMessage("Error: you must select a robot");
     return;
   }
   // get run type
   if (!ui->simulatorButton->isChecked() && !ui->robotButton->isChecked()) {
     createErrorMessage(
         "Error: you must select either robot or simulation mode");
     return;
   }
   _simulationMode = ui->simulatorButton->isChecked();
   // graphics
   printf("[SimControlPanel] Initialize Graphics...\n");
   _graphicsWindow = new Graphics3D();
   _graphicsWindow->show();
   _graphicsWindow->resize(1280, 720);
   if (_simulationMode) {
     // run a simulation
     try {
       printf("[SimControlPanel] Initialize simulator...\n");
       _simulation = new Simulation(robotType, _graphicsWindow, _parameters, _userParameters,
         // this will allow the simulation thread to poke us when there's a state change
         [this](){
         QMetaObject::invokeMethod(this,"update_ui");
       });
       loadSimulationParameters(_simulation->getSimParams());
       loadRobotParameters(_simulation->getRobotParams());
       // terrain
       printf("[SimControlParameter] Load terrain...\n");
       _simulation->loadTerrainFile(_terrainFileName);
     } catch (std::exception& e) {
       createErrorMessage("FATAL: Exception thrown during simulator setup\n" + std::string(e.what()));
       throw e;
     }
     // start sim
     _simThread = std::thread(
       // simulation function
       [this]() {
         // error callback function
         std::function<void(std::string)> error_function = [this](std::string str) {
           // Qt will take care of doing the call in the UI event loop
           QMetaObject::invokeMethod(this, [=]() {
             this->errorCallback(str);
           });
         };
         try {
           // pass error callback to simulator
           _simulation->runAtSpeed(error_function);
         } catch (std::exception &e) {
           // also catch exceptions
           error_function("Exception thrown in simulation thread: " + std::string(e.what()));
         }
       });
     // graphics start
     _graphicsWindow->setAnimating(true);
   } else {
     printf("[SimControlPanel] Init Robot Interface...\n");
     _interfaceTaskManager = new PeriodicTaskManager;
     _robotInterface =
         new RobotInterface(robotType, _graphicsWindow, _interfaceTaskManager, _userParameters);
     loadRobotParameters(_robotInterface->getParams());
     _robotInterface->startInterface();
     _graphicsWindow->setAnimating(true);
   }
   _state = SimulationWindowState::RUNNING;
   updateUiEnable();
 }
References _graphicsWindow, _interfaceTaskManager, _parameters, _robotInterface, _simThread, _simulation, _simulationMode, _state, _terrainFileName, _userParameters, CHEETAH_3, createErrorMessage(), errorCallback(), RobotInterface::getParams(), Simulation::getRobotParams(), Simulation::getSimParams(), loadRobotParameters(), loadSimulationParameters(), Simulation::loadTerrainFile(), MINI_CHEETAH, Simulation::runAtSpeed(), RUNNING, Graphics3D::setAnimating(), RobotInterface::startInterface(), ui, and updateUiEnable().
on_stopButton_clicked
void SimControlPanel::on_stopButton_clicked () private slot
Stop the currently running simulation or robot connection
Definition at line 440 of file SimControlPanel.cpp.
{
   if (_simulation) {
     _simulation->stop();
     _simThread.join();
   } else {
     _robotInterface->stopInterface();
   }
   if (_graphicsWindow) {
     _graphicsWindow->setAnimating(false);
     _graphicsWindow->hide();
   }
   delete _interfaceTaskManager;
   delete _robotInterface;
   delete _simulation;
   delete _graphicsWindow;
   _simulation = nullptr;
   _graphicsWindow = nullptr;
   _robotInterface = nullptr;
   _interfaceTaskManager = nullptr;
   _state = SimulationWindowState::STOPPED;
   updateUiEnable();
 }
References _graphicsWindow, _interfaceTaskManager, _robotInterface, _simThread, _simulation, _state, Graphics3D::setAnimating(), Simulation::stop(), RobotInterface::stopInterface(), STOPPED, and updateUiEnable().
on_userControlTable_cellChanged
void SimControlPanel::on_userControlTable_cellChanged (int row, int column) private slot
Definition at line 742 of file SimControlPanel.cpp.
{
   if (_ignoreTableCallbacks) return;
   if (column != 1) {
     return;
   }
   auto cell = ui->userControlTable->item(row, 0);
   std::string cellName = cell->text().toStdString();
   if (cellName == "") {
     return;
   }
   auto& parameter = _userParameters.collection.lookup(cellName);
 //  auto& parameter = (_simulationMode ? _simulation->getRobotParams()
 //                                     : _robotInterface->getParams())
 //      .collection.lookup(cellName);
   ControlParameterValueKind kind = parameter._kind;
   ControlParameterValue oldValue = parameter.get(kind);
   bool success = true;
   try {
     parameter.setFromString(ui->userControlTable->item(row, 1)->text().toStdString());
   } catch (std::exception& e) {
     success = false;
   }
   if (!success) {
     printf("[ERROR] invalid data, restoring old data!\n");
     parameter.set(oldValue, kind);
     assert(!_ignoreTableCallbacks);
     _ignoreTableCallbacks = true;
     ui->userControlTable->item(row, 1)->setText(
         QString(_userParameters
                     .collection.lookup(cellName)
                     .toString()
                     .c_str()));
     _ignoreTableCallbacks = false;
   } else {
     if(isRunning() || isError()) {
       if (_simulationMode) {
         if (_simulation && _simulation->isRobotConnected()) {
           _simulation->sendControlParameter(
               cellName, parameter.get(parameter._kind), parameter._kind, true);
         }
         _ignoreTableCallbacks = true;
         ui->userControlTable->item(row, 1)->setText(
             QString(parameter.toString().c_str()));
         _ignoreTableCallbacks = false;
       } else {
       _robotInterface->sendControlParameter(
           cellName, parameter.get(parameter._kind), parameter._kind, true);
       }
     }
   }
 }
References _ignoreTableCallbacks, ControlParameter::_kind, _robotInterface, _simulation, _simulationMode, _userParameters, ControlParameters::collection, isError(), Simulation::isRobotConnected(), isRunning(), ControlParameterCollection::lookup(), RobotInterface::sendControlParameter(), Simulation::sendControlParameter(), and ui.
pointsLCMThread()
void SimControlPanel::pointsLCMThread () inline private
Definition at line 143 of file SimControlPanel.h.
 { while (true) { _pointsLCM.handle(); } }
References _pointsLCM.
update_ui
void SimControlPanel::update_ui () slot
External notification of UI update needed
Definition at line 285 of file SimControlPanel.cpp.
{
   updateUiEnable();
 }
References updateUiEnable().
updateTerrainLabel
void SimControlPanel::updateTerrainLabel () private slot
Update the name of the loaded terrain file label
Definition at line 329 of file SimControlPanel.cpp.
{
   ui->terrainFileLabel->setText(QString(_terrainFileName.c_str()));
 }
References _terrainFileName, and ui.
updateUiEnable()
void SimControlPanel::updateUiEnable () private
Enable/disable buttons as needed based on what is running
Definition at line 292 of file SimControlPanel.cpp.
{
   ui->startButton->setEnabled(!(isRunning() || isError()));
   ui->stopButton->setEnabled(isRunning() || isError());
   ui->joystickButton->setEnabled(isRunning() || isError());
   ui->robotTable->setEnabled(isRunning() || isError());
   ui->goHomeButton->setEnabled(isRunning() || isError());
   switch(_state) {
     case SimulationWindowState::STOPPED:
       ui->simulatorStateLabel->setText("Simulator State: Stopped");
       ui->stopButton->setText("Stop");
       break;
     case SimulationWindowState::RUNNING:
       ui->simulatorStateLabel->setText("Simulator State: Running");
       ui->stopButton->setText("Stop");
       break;
     case SimulationWindowState::ERROR:
       ui->simulatorStateLabel->setText("Simulator State: Error");
       ui->stopButton->setText("Reset Error");
       break;
   }
   if((isRunning() || isError()) && _simulation) {
     if(_simulation->isRobotConnected()) {
       ui->simulatorConnectedLabel->setText("Sim Connection: Yes");
     } else {
       ui->simulatorConnectedLabel->setText("Sim Connection: No");
     }
   } else {
     ui->simulatorConnectedLabel->setText("Sim Connection: N/A");
   }
 }
References _simulation, _state, ERROR, isError(), Simulation::isRobotConnected(), isRunning(), RUNNING, STOPPED, and ui.
Member Data Documentation
_ctrlVisionLCM
lcm::LCM SimControlPanel::_ctrlVisionLCM private
Definition at line 160 of file SimControlPanel.h.
_ctrlVisionLCMThread
std::thread SimControlPanel::_ctrlVisionLCMThread private
Definition at line 166 of file SimControlPanel.h.
_firstStart
bool SimControlPanel::_firstStart = true private
Definition at line 131 of file SimControlPanel.h.
_graphicsWindow
Graphics3D* SimControlPanel::_graphicsWindow = nullptr private
Definition at line 127 of file SimControlPanel.h.
_heightmapLCM
lcm::LCM SimControlPanel::_heightmapLCM private
Definition at line 157 of file SimControlPanel.h.
_heightmapLCMThread
std::thread SimControlPanel::_heightmapLCMThread private
Definition at line 164 of file SimControlPanel.h.
_ignoreTableCallbacks
bool SimControlPanel::_ignoreTableCallbacks = false private
Definition at line 132 of file SimControlPanel.h.
_indexmapLCM
lcm::LCM SimControlPanel::_indexmapLCM private
Definition at line 159 of file SimControlPanel.h.
_indexmapLCMThread
std::thread SimControlPanel::_indexmapLCMThread private
Definition at line 165 of file SimControlPanel.h.
_interfaceTaskManager
PeriodicTaskManager* SimControlPanel::_interfaceTaskManager = nullptr private
Definition at line 125 of file SimControlPanel.h.
_loadedUserSettings
bool SimControlPanel::_loadedUserSettings = false private
Definition at line 133 of file SimControlPanel.h.
_mcDebugWindow
MiniCheetahDebug SimControlPanel::_mcDebugWindow private
Definition at line 169 of file SimControlPanel.h.
_miniCheetahDebugLCM
lcm::LCM SimControlPanel::_miniCheetahDebugLCM private
Definition at line 161 of file SimControlPanel.h.
_miniCheetahDebugLCMThread
std::thread SimControlPanel::_miniCheetahDebugLCMThread private
Definition at line 167 of file SimControlPanel.h.
_parameters
SimulatorControlParameters SimControlPanel::_parameters private
Definition at line 128 of file SimControlPanel.h.
_pointsLCM
lcm::LCM SimControlPanel::_pointsLCM private
Definition at line 158 of file SimControlPanel.h.
_pointsLCMThread
std::thread SimControlPanel::_pointsLCMThread private
Definition at line 163 of file SimControlPanel.h.
_robotInterface
RobotInterface* SimControlPanel::_robotInterface = nullptr private
Definition at line 126 of file SimControlPanel.h.
_simThread
std::thread SimControlPanel::_simThread private
Definition at line 120 of file SimControlPanel.h.
_simulation
Simulation* SimControlPanel::_simulation = nullptr private
Definition at line 124 of file SimControlPanel.h.
_simulationMode
bool SimControlPanel::_simulationMode = false private
Definition at line 130 of file SimControlPanel.h.
_state
SimulationWindowState SimControlPanel::_state = SimulationWindowState::STOPPED private
Definition at line 122 of file SimControlPanel.h.
_terrainFileName
std::string SimControlPanel::_terrainFileName private
Definition at line 134 of file SimControlPanel.h.
_userParameters
ControlParameters SimControlPanel::_userParameters private
Definition at line 129 of file SimControlPanel.h.
ui
Ui::SimControlPanel* SimControlPanel::ui private
Definition at line 123 of file SimControlPanel.h.
The documentation for this class was generated from the following files:
SimControlPanel.h
SimControlPanel.cpp