Cheetah Software: DrawList Class Reference
DrawList Class Reference
#include <DrawList.h>
Public Member Functions
DrawList ()
size_t addCheetah3 (Vec4< float > color, bool useOld, bool canHide)
size_t addMiniCheetah (Vec4< float > color, bool useOld, bool canHide)
void buildDrawList ()
void loadFiles ()
void doScrolling (Vec3< float > cameraPos)
size_t addCheckerboard (Checkerboard &checkerBoard, bool setScrolling)
size_t addDebugSphere (float radius)
void addBox (double depth, double width, double height, const Vec3< double > &pos, const Mat3< double > &ori, bool transparent)
void addMesh (double grid_size, const Vec3< double > &left_corner, const DMat< double > &height_map, bool transparent)
void resize (size_t nUniqueObject, size_t nTotalObjects)
size_t getNumObjectsToDraw ()
size_t getGLDrawArrayOffset (size_t i)
size_t getGLDrawArraySize (size_t i)
bool getCanBeHidden (size_t i)
float * getVertexArray ()
float * getNormalArray ()
size_t getSizeOfAllData ()
float * getColorArray ()
QMatrix4x4 & getModelBaseTransform (size_t i)
QMatrix4x4 & getModelKinematicTransform (size_t i)
float getGLDataSizeMB ()
bool needsReload ()
template<typename T >
void updateRobotFromModel (DynamicsSimulator< T > &model, size_t id, bool updateOrigin=false)
template<typename T >
void updateAdditionalInfo (DynamicsSimulator< T > &model)
template<typename T >
void updateCheckerboardFromCollisionPlane (CollisionPlane< T > &model, size_t id)
template<typename T >
void updateCheckerboard (T height, size_t id)
template<typename T >
void updateDebugSphereLocation (Vec3< T > &position, size_t id)
const size_t & getTotalNumGC ()
const std::vector< double > & getGCPos (size_t idx)
const std::vector< double > & getGCForce (size_t idx)
const std::vector< BoxInfo > & getBoxInfoList ()
const DMat< double > & getHeightMap ()
const Vec3< double > & getHeightMapLeftCorner ()
const double & getHeightMapMax ()
const double & getHeightMapMin ()
const double & getGridSize ()
const Vec3< double > & getCameraOrigin ()
Static Public Member Functions
static void setSolidColor (std::vector< float > &data, size_t size, float r, float g, float b)
Public Attributes
VisualizationData * _visualizationData
vectorAligned< SolidColor > _instanceColor
std::vector< QMatrix4x4 > _kinematicXform
Private Attributes
size_t _nUnique = 0
size_t _nTotal = 0
std::vector< std::vector< float > > _vertexData
std::vector< std::vector< float > > _normalData
std::vector< std::vector< float > > _colorData
std::vector< u8 > _canBeHidden
vectorAligned< Mat4< float > > _offsetXforms
std::string _baseFileName = "../resources/"
std::vector< size_t > _objectMap
std::vector< size_t > _glArrayOffsets
std::vector< size_t > _glArraySizes
std::vector< float > _glVertexData
std::vector< float > _glNormalData
std::vector< float > _glColorData
std::vector< ScrollInfo > _scrollIDs
std::vector< QMatrix4x4 > _modelOffsets
bool _reloadNeeded = false
bool _additionalInfoFirstVisit = true
size_t _nTotalGC = 0
std::vector< bool > _cp_touch
std::vector< std::vector< double > > _cp_pos
std::vector< std::vector< double > > _cp_force
std::vector< BoxInfo > _box_list
double _grid_size
Vec3< double > _height_map_left_corner
DMat< double > _height_map
double _height_map_max
double _height_map_min
Vec3< double > _cameraOrigin
size_t _cheetah3LoadIndex = 0
size_t _miniCheetahLoadIndex = 0
size_t _sphereLoadIndex = 0
size_t _cubeLoadIndex = 0
Detailed Description
Definition at line 54 of file DrawList.h.
Constructor & Destructor Documentation
DrawList()
DrawList::DrawList () inline
Definition at line 58 of file DrawList.h.
              {
     _cameraOrigin = Vec3<double>::Zero();
     loadFiles();
   }
References _cameraOrigin, and loadFiles().
Member Function Documentation
addBox()
void DrawList::addBox (double depth, double width, double height, const Vec3< double > & pos, const Mat3< double > & ori, bool transparent)
Definition at line 318 of file DrawList.cpp.
{
   if (transparent) {
     BoxInfo tmp;
     tmp.depth = depth;
     tmp.width = width;
     tmp.height = height;
     tmp.frame[3] = 0.;
     tmp.frame[7] = 0.;
     tmp.frame[11] = 0.;
     tmp.frame[15] = 1.;
     for (size_t i(0); i < 3; ++i) {
       for (size_t j(0); j < 3; ++j) {
         tmp.frame[4 * i + j] = ori(j, i);
       }
     }
     for (size_t i(0); i < 3; ++i) tmp.frame[12 + i] = pos[i];
     _box_list.push_back(tmp);
   } else {
     QMatrix4x4 offset;
     // scale box
     offset.setToIdentity();
     offset.scale(depth, width, height);
     _modelOffsets.push_back(offset);
     // move box
     offset.setToIdentity();
     offset.translate(pos[0], pos[1], pos[2]);
     Quat<double> q = ori::rotationMatrixToQuaternion(ori.transpose());
     QQuaternion qq(q[0], q[1], q[2], q[3]);
     offset.rotate(qq);
     _kinematicXform.push_back(offset);
     SolidColor boxColor;
     boxColor.rgba = Vec4<float>(disgustingGreen[0], disgustingGreen[1],
                                 disgustingGreen[2], 1.f);
     boxColor.useSolidColor = true;
     _instanceColor.push_back(boxColor);
     _nTotal++;
     _objectMap.push_back(_cubeLoadIndex);
     _canBeHidden.push_back(false);
   }
 }
References _box_list, _canBeHidden, _cubeLoadIndex, _instanceColor, _kinematicXform, _modelOffsets, _nTotal, _objectMap, BoxInfo::depth, disgustingGreen, BoxInfo::frame, BoxInfo::height, SolidColor::rgba, ori::rotationMatrixToQuaternion(), SolidColor::useSolidColor, and BoxInfo::width.
addCheckerboard()
size_t DrawList::addCheckerboard (Checkerboard & checkerBoard, bool scroll)
Adds a checkerboard to the list of drawables. Uses an identity transformation. You must call updateCheckerboardFromCollisionPlane to set the actual transform.
Definition at line 231 of file DrawList.cpp.
{
   size_t j0 = _nTotal;
   size_t i0 = _nUnique;
   SolidColor checkerColor;
   checkerColor.useSolidColor = false;
   _nUnique++;
   // add the object
   _vertexData.emplace_back();
   _normalData.emplace_back();
   _colorData.emplace_back();
   checkerBoard.computeVertices(_vertexData.back(), _normalData.back(),
                                _colorData.back());
   QMatrix4x4 eye, offset;
   eye.setToIdentity();
   offset.setToIdentity();
   offset.translate(-checkerBoard.getSize()[0] / 2,
                    -checkerBoard.getSize()[1] / 2);
   _modelOffsets.push_back(offset);
   _kinematicXform.push_back(eye);
   _instanceColor.push_back(checkerColor);
   _nTotal++;
   // add the instance
   _objectMap.push_back(i0);
   _canBeHidden.push_back(false);
   if(scroll) {
     _scrollIDs.push_back({j0, checkerBoard.getSize()[0], checkerBoard.getSize()[1]});
   }
   return j0;
 }
References _canBeHidden, _colorData, _instanceColor, _kinematicXform, _modelOffsets, _normalData, _nTotal, _nUnique, _objectMap, _scrollIDs, _vertexData, Checkerboard::computeVertices(), Checkerboard::getSize(), and SolidColor::useSolidColor.
addCheetah3()
size_t DrawList::addCheetah3 (Vec4< float > color, bool useOld, bool canHide)
Load the cheetah 3 model and build the draw list. Returns an index number that can later be used to update the position of the robot.
Definition at line 48 of file DrawList.cpp.
{
   size_t i0 = _cheetah3LoadIndex;
   size_t j0 = _nTotal;
   // set model offsets:
   QMatrix4x4 bodyOffset, abadOffset, lowerOffset, eye;
   eye.setToIdentity();
   QMatrix4x4 upperOffsets[2];
   // body
   bodyOffset.setToIdentity();
   bodyOffset.rotate(90, 1, 0, 0);
   bodyOffset.rotate(90, 0, 0, 1);
   // abad
   abadOffset.setToIdentity();
   // upper link
   upperOffsets[0].setToIdentity();
   upperOffsets[0].rotate(-180, 0, 1, 0);
   upperOffsets[0].translate(0, -.045f, 0);
   upperOffsets[0].rotate(-180, 0, 0, 1);
   upperOffsets[1].setToIdentity();
   upperOffsets[1].rotate(-180, 0, 1, 0);
   upperOffsets[1].translate(0, .045f, 0);
   lowerOffset.setToIdentity();
   lowerOffset.rotate(180, 0, 1, 0);
   lowerOffset.translate(0, 0, 0);
   SolidColor bodyColor, abadColor, link1Color, link2Color;
   bodyColor.rgba = useOld ? Vec4<float>(.2, .2, .4, .3) : color;
   bodyColor.useSolidColor = true;
   abadColor.rgba = useOld ? Vec4<float>(.2, .2, .4, .3) : color;
   abadColor.useSolidColor = true;
   link1Color.rgba = useOld ? Vec4<float>(.2, .2, .4, .3) : color;
   link1Color.useSolidColor = true;
   link2Color.rgba = useOld ? Vec4<float>(.2, .2, .4, .3) : color;
   link2Color.useSolidColor = true;
   _canBeHidden.push_back(canHide);
   // add bodies
   _objectMap.push_back(i0 + 0);
   _modelOffsets.push_back(bodyOffset);
   _kinematicXform.push_back(eye);
   _instanceColor.push_back(bodyColor);
   _nTotal++;
   for (int i = 0; i < 4; i++) {
     _objectMap.push_back(i0 + 1);
     _canBeHidden.push_back(canHide);
     _modelOffsets.push_back(abadOffset);
     _kinematicXform.push_back(eye);
     _instanceColor.push_back(abadColor);
     _objectMap.push_back(i0 + 2);
     _canBeHidden.push_back(canHide);
     _modelOffsets.push_back(upperOffsets[i % 2]);
     _kinematicXform.push_back(eye);
     _instanceColor.push_back(link1Color);
     _objectMap.push_back(i0 + 3);
     _canBeHidden.push_back(canHide);
     _modelOffsets.push_back(lowerOffset);
     _kinematicXform.push_back(eye);
     _instanceColor.push_back(link2Color);
     _nTotal += 3;
   }
   printf("size of kinematicXform: %lu, j0: %lu\n", _kinematicXform.size(), j0);
   buildDrawList();
   return j0;
 }
References _canBeHidden, _cheetah3LoadIndex, _instanceColor, _kinematicXform, _modelOffsets, _nTotal, _objectMap, buildDrawList(), SolidColor::rgba, and SolidColor::useSolidColor.
addDebugSphere()
size_t DrawList::addDebugSphere (float radius)
Adds a sphere to the list of drawables.
Definition at line 276 of file DrawList.cpp.
{
   assert(false);
   size_t j0 = _nTotal;
   QMatrix4x4 offset;
   offset.setToIdentity();
   _kinematicXform.push_back(offset);
   offset.scale(radius);
   _modelOffsets.push_back(offset);
   _nTotal++;
   _objectMap.push_back(_sphereLoadIndex);
   _canBeHidden.push_back(false);
   return j0;
 }
References _canBeHidden, _kinematicXform, _modelOffsets, _nTotal, _objectMap, and _sphereLoadIndex.
addMesh()
void DrawList::addMesh (double grid_size, const Vec3< double > & left_corner, const DMat< double > & height_map, bool transparent)
Definition at line 369 of file DrawList.cpp.
{
   (void)transparent;
   _grid_size = grid_size;
   _height_map_left_corner = left_corner;
   _height_map = height_map;
   _height_map_min = 1.e5;
   _height_map_max = -1.e5;
   for (int i(0); i < height_map.rows(); ++i) {
     for (int j(0); j < height_map.cols(); ++j) {
       if (height_map(i, j) > _height_map_max) {
         _height_map_max = height_map(i, j);
       }
       if (height_map(i, j) < _height_map_min) {
         _height_map_min = height_map(i, j);
       }
     }
   }
 }
References _grid_size, _height_map, _height_map_left_corner, _height_map_max, and _height_map_min.
addMiniCheetah()
size_t DrawList::addMiniCheetah (Vec4< float > color, bool useOld, bool canHide)
Load the mini cheetah model and builds the draw list. Returns an index number that can later be used to update the position of the robot. TODO check all this once the mini cheetah dynamics model exists again
Definition at line 134 of file DrawList.cpp.
{
   size_t i0 = _miniCheetahLoadIndex;  // todo don't hard code this
   size_t j0 = _nTotal;
   // set model offsets:
   QMatrix4x4 bodyOffset, upper, lower, eye;
   QMatrix4x4 abadOffsets[4];
   eye.setToIdentity();
   // body
   bodyOffset.setToIdentity();
   // abads (todo, check these)
   abadOffsets[0].setToIdentity();  // n
   abadOffsets[0].rotate(-90, 0, 0, 1);
   abadOffsets[0].translate(0, -.0565f, 0);
   abadOffsets[0].rotate(180, 0, 1, 0);
   abadOffsets[1].setToIdentity();  // p
   abadOffsets[1].rotate(-90, 0, 0, 1);
   abadOffsets[1].translate(0, -.0565f, 0);
   abadOffsets[1].rotate(0, 0, 1, 0);
   abadOffsets[2].setToIdentity();  // n
   abadOffsets[2].rotate(90, 0, 0, 1);
   abadOffsets[2].translate(0, -.0565f, 0);
   abadOffsets[2].rotate(0, 0, 1, 0);
   abadOffsets[3].setToIdentity();  // p
   abadOffsets[3].rotate(90, 0, 0, 1);
   abadOffsets[3].translate(0, -.0565f, 0);
   abadOffsets[3].rotate(180, 0, 1, 0);
   // upper
   upper.setToIdentity();
   upper.rotate(-90, 0, 1, 0);
   // lower
   lower.setToIdentity();
   lower.rotate(180, 0, 1, 0);
   SolidColor bodyColor, abadColor, link1Color, link2Color;
   bodyColor.rgba = useOld ? Vec4<float>(.2, .2, .4, .3) : color;
   bodyColor.useSolidColor = true;
   abadColor.rgba = useOld ? Vec4<float>(.2, .2, .4, .3) : color;
   abadColor.useSolidColor = true;
   link1Color.rgba = useOld ? Vec4<float>(.2, .2, .4, .3) : color;
   link1Color.useSolidColor = true;
   link2Color.rgba = useOld ? Vec4<float>(.2, .2, .4, .3) : color;
   link2Color.useSolidColor = true;
   _canBeHidden.push_back(canHide);
   // add objects
   _objectMap.push_back(i0 + 0);
   _modelOffsets.push_back(bodyOffset);
   _kinematicXform.push_back(eye);
   _instanceColor.push_back(bodyColor);
   _nTotal++;
   for (int i = 0; i < 4; i++) {
     _objectMap.push_back(i0 + 1);
     _canBeHidden.push_back(canHide);
     _modelOffsets.push_back(abadOffsets[i]);
     _kinematicXform.push_back(eye);
     _instanceColor.push_back(abadColor);
     _objectMap.push_back(i0 + 2);
     _canBeHidden.push_back(canHide);
     _modelOffsets.push_back(upper);
     _kinematicXform.push_back(eye);
     _instanceColor.push_back(link1Color);
     _objectMap.push_back(i0 + 3);
     _canBeHidden.push_back(canHide);
     _modelOffsets.push_back(lower);
     _kinematicXform.push_back(eye);
     _instanceColor.push_back(link2Color);
     _nTotal += 3;
   }
   // printf("add mini cheetah (%d) id %ld\n", (int)canHide, j0);
   // for(u32 i = 0; i < _canBeHidden.size(); i++) {
   //   printf(" [%02d] %d\n", i, _canBeHidden[i]);
   // }
   return j0;
 }
References _canBeHidden, _instanceColor, _kinematicXform, _miniCheetahLoadIndex, _modelOffsets, _nTotal, _objectMap, SolidColor::rgba, and SolidColor::useSolidColor.
buildDrawList()
void DrawList::buildDrawList ()
Rebuilds the drawing list and sets the flag indicating that model data must be reloaded.
Definition at line 296 of file DrawList.cpp.
{
   _glVertexData.clear();
   _glColorData.clear();
   _glNormalData.clear();
   _glArrayOffsets.clear();
   _glArraySizes.clear();
   for (size_t i = 0; i < _nUnique; i++) {
     _glArrayOffsets.push_back(_glVertexData.size());
     _glArraySizes.push_back(_vertexData.at(i).size());
     // add the data for the objects
     _glVertexData.insert(_glVertexData.end(), _vertexData.at(i).begin(),
                          _vertexData.at(i).end());
     _glColorData.insert(_glColorData.end(), _colorData.at(i).begin(),
                         _colorData.at(i).end());
     _glNormalData.insert(_glNormalData.end(), _normalData.at(i).begin(),
                          _normalData.at(i).end());
   }
   _reloadNeeded = true;
 }
References _colorData, _glArrayOffsets, _glArraySizes, _glColorData, _glNormalData, _glVertexData, _normalData, _nUnique, _reloadNeeded, and _vertexData.
doScrolling()
void DrawList::doScrolling (Vec3< float > cameraPos)
Definition at line 264 of file DrawList.cpp.
{
   for(auto& obj : _scrollIDs) {
     float scrollDiv[2] = {obj.xs/4, obj.ys/4};
     auto& groundXform = getModelKinematicTransform(obj.id);
     groundXform.setToIdentity();
     groundXform.translate( -scrollDiv[0] * (int)(cameraPos[0] / scrollDiv[0]),  -scrollDiv[1] * (int)(cameraPos[1] / scrollDiv[1]));
   }
 }
References _scrollIDs, and getModelKinematicTransform().
getBoxInfoList()
const std::vector<BoxInfo>& DrawList::getBoxInfoList () inline
Definition at line 277 of file DrawList.h.
 { return _box_list; }
References _box_list.
getCameraOrigin()
const Vec3<double>& DrawList::getCameraOrigin () inline
Definition at line 287 of file DrawList.h.
 { return _cameraOrigin; }
References _cameraOrigin.
getCanBeHidden()
bool DrawList::getCanBeHidden (size_t i) inline
Definition at line 110 of file DrawList.h.
{
     return _canBeHidden.at(i);
   }
References _canBeHidden.
getColorArray()
float* DrawList::getColorArray () inline
Get the array containing all color data.
Definition at line 131 of file DrawList.h.
 { return _glColorData.data(); }
References _glColorData.
getGCForce()
const std::vector<double>& DrawList::getGCForce (size_t idx) inline
Definition at line 276 of file DrawList.h.
 { return _cp_force[idx]; }
References _cp_force.
getGCPos()
const std::vector<double>& DrawList::getGCPos (size_t idx) inline
Definition at line 275 of file DrawList.h.
 { return _cp_pos[idx]; }
References _cp_pos.
getGLDataSizeMB()
float DrawList::getGLDataSizeMB () inline
Get size of data used by the GPU in megabytes For debugging
Definition at line 152 of file DrawList.h.
{
     size_t bytes =
         _glColorData.size() + _glNormalData.size() + _glVertexData.size();
     bytes = bytes * sizeof(float);
     return (float)bytes / float(1 << 20);
   }
References _glColorData, _glNormalData, and _glVertexData.
getGLDrawArrayOffset()
size_t DrawList::getGLDrawArrayOffset (size_t i) inline
For the i-th object, get the offset into the model data. For use with the glDrawArrays function. Note that several objects may have the same geometry, so this will return the same value for these objects!
Definition at line 99 of file DrawList.h.
{
     return _glArrayOffsets.at(_objectMap.at(i));
   }
References _glArrayOffsets, and _objectMap.
getGLDrawArraySize()
size_t DrawList::getGLDrawArraySize (size_t i) inline
For the i-th object, get the size of the model data array
Definition at line 106 of file DrawList.h.
{
     return _glArraySizes.at(_objectMap.at(i));
   }
References _glArraySizes, and _objectMap.
getGridSize()
const double& DrawList::getGridSize () inline
Definition at line 285 of file DrawList.h.
 { return _grid_size; }
References _grid_size.
getHeightMap()
const DMat<double>& DrawList::getHeightMap () inline
Definition at line 279 of file DrawList.h.
 { return _height_map; }
References _height_map.
getHeightMapLeftCorner()
const Vec3<double>& DrawList::getHeightMapLeftCorner () inline
Definition at line 280 of file DrawList.h.
{
     return _height_map_left_corner;
   }
References _height_map_left_corner.
getHeightMapMax()
const double& DrawList::getHeightMapMax () inline
Definition at line 283 of file DrawList.h.
 { return _height_map_max; }
References _height_map_max.
getHeightMapMin()
const double& DrawList::getHeightMapMin () inline
Definition at line 284 of file DrawList.h.
 { return _height_map_min; }
References _height_map_min.
getModelBaseTransform()
QMatrix4x4& DrawList::getModelBaseTransform (size_t i) inline
Get the Qt transformation matrix which should be applied to the model geometry This is to correct for errors when exporting parts and shifts them all to the origin.
Definition at line 138 of file DrawList.h.
 { return _modelOffsets[i]; }
References _modelOffsets.
getModelKinematicTransform()
QMatrix4x4& DrawList::getModelKinematicTransform (size_t i) inline
Get the Qt transformation matrix which should be applied to move a model from the origin to where it should be in the world
Definition at line 144 of file DrawList.h.
{
     return _kinematicXform[i];
   }
References _kinematicXform.
getNormalArray()
float* DrawList::getNormalArray () inline
Get the array containing all normal data. Use getGLDrawArrayOffset/Size to get indices and sizes for each object
Definition at line 124 of file DrawList.h.
 { return _glNormalData.data(); }
References _glNormalData.
getNumObjectsToDraw()
size_t DrawList::getNumObjectsToDraw () inline
Get the total number of objects to be drawn
Definition at line 91 of file DrawList.h.
 { return _nTotal; }
References _nTotal.
getSizeOfAllData()
size_t DrawList::getSizeOfAllData () inline
Definition at line 126 of file DrawList.h.
 { return _glVertexData.size(); }
References _glVertexData.
getTotalNumGC()
const size_t& DrawList::getTotalNumGC () inline
Definition at line 274 of file DrawList.h.
 { return _nTotalGC; }
References _nTotalGC.
getVertexArray()
float* DrawList::getVertexArray () inline
Get the array containing all vertex data. Use getGLDrawArrayOffset/Size to get indices and sizes for each object
Definition at line 118 of file DrawList.h.
 { return _glVertexData.data(); }
References _glVertexData.
loadFiles()
void DrawList::loadFiles ()
Definition at line 10 of file DrawList.cpp.
{
   printf("[DrawList] Load object files...\n");
   std::vector<std::string> names = {
       "c3_body.obj",         "mini_abad.obj",
       "c3_upper_link.obj",   "c3_lower_link.obj",
       "mini_body.obj",       "mini_abad.obj",
       "mini_upper_link.obj", "mini_lower_link.obj",
       "sphere.obj",          "cube.obj"};
   for (const auto& name : names) {
     std::string filename = _baseFileName + name;
     _vertexData.emplace_back();
     _normalData.emplace_back();
     _colorData.emplace_back();
     load_obj_file(filename, _vertexData.back(), _normalData.back());
     if (name == "sphere.obj") {
       setSolidColor(_colorData.back(), _vertexData.back().size(),
                     debugRedColor[0], debugRedColor[1], debugRedColor[2]);
     } else if (name == "cube.obj") {
       setSolidColor(_colorData.back(), _vertexData.back().size(),
                     disgustingGreen[0], disgustingGreen[1], disgustingGreen[2]);
     } else {
       setSolidColor(_colorData.back(), _vertexData.back().size(),
                     defaultRobotColor[0], defaultRobotColor[1],
                     defaultRobotColor[2]);
     }
     _nUnique++;
   }
   _sphereLoadIndex = 8;
   _cubeLoadIndex = 9;
   _miniCheetahLoadIndex = 4;
   _cheetah3LoadIndex = 0;
 }
References _baseFileName, _cheetah3LoadIndex, _colorData, _cubeLoadIndex, _miniCheetahLoadIndex, _normalData, _nUnique, _sphereLoadIndex, _vertexData, debugRedColor, defaultRobotColor, disgustingGreen, load_obj_file(), and setSolidColor().
needsReload()
bool DrawList::needsReload () inline
Returns true a single time if we have changed geometries and need to reload.
Definition at line 163 of file DrawList.h.
                      {
     if (_reloadNeeded) {
       _reloadNeeded = false;
       return true;
     }
     return false;
   }
References _reloadNeeded.
resize()
void DrawList::resize (size_t nUniqueObject, size_t nTotalObjects) inline
Resize to hold size objects.
Definition at line 78 of file DrawList.h.
{
     _nUnique = nUniqueObject;
     _nTotal = nTotalObjects;
     _vertexData.resize(nUniqueObject);
     _normalData.resize(nUniqueObject);
     _colorData.resize(nUniqueObject);
     _offsetXforms.resize(nUniqueObject);
     _objectMap.resize(nTotalObjects);
   }
References _colorData, _normalData, _nTotal, _nUnique, _objectMap, _offsetXforms, and _vertexData.
setSolidColor()
static void DrawList::setSolidColor (std::vector< float > & data, size_t size, float r, float g, float b) inline static
Fill color data with a solid color
Definition at line 257 of file DrawList.h.
{
     data.clear();
     data.resize(size);
     if ((size % 3) != 0) {
       throw std::runtime_error("setSolidColor invalid size");
     }
     for (size_t i = 0; i < size / 3; i++) {
       data[i * 3 + 0] = r;
       data[i * 3 + 1] = g;
       data[i * 3 + 2] = b;
     }
   }
updateAdditionalInfo()
template<typename T > void DrawList::updateAdditionalInfo (DynamicsSimulator< T > & model) inline
Update the additional information drawn by GUI Doesn't run the simulator
just pulls contact (or other in the future) data from the DynamicsSimulator
Parameters
model : the simulator
Definition at line 201 of file DrawList.h.
{
     if (_additionalInfoFirstVisit) {
       _nTotalGC = model.getTotalNumGC();
       _cp_touch.resize(_nTotalGC, false);
       _cp_pos.resize(_nTotalGC);
       _cp_force.resize(_nTotalGC);
       std::vector<double> tmp(3);
       for (size_t i(0); i < _nTotalGC; ++i) {
         _cp_pos[i] = tmp;
         _cp_force[i] = tmp;
       }
       _additionalInfoFirstVisit = false;
     }
     for (size_t i(0); i < _nTotalGC; ++i) {
       // TODO: check touch boolean
       _cp_touch[i] = true;
       for (size_t j(0); j < 3; ++j) {
         _cp_pos[i][j] = model.getModel()._pGC[i][j];
         _cp_force[i][j] = model.getContactForce(i)[j];
       }
     }
   }
References _additionalInfoFirstVisit, _cp_force, _cp_pos, _cp_touch, _nTotalGC, DynamicsSimulator< T >::getContactForce(), DynamicsSimulator< T >::getModel(), and DynamicsSimulator< T >::getTotalNumGC().
updateCheckerboard()
template<typename T > void DrawList::updateCheckerboard (T height, size_t id) inline
Definition at line 239 of file DrawList.h.
{
     QMatrix4x4 H;
     H.setToIdentity();
     H.translate(0., 0., height);
     _kinematicXform.at(id) = H;
   }
References _kinematicXform.
updateCheckerboardFromCollisionPlane()
template<typename T > void DrawList::updateCheckerboardFromCollisionPlane (CollisionPlane< T > & model, size_t id) inline
Updates the position of a checkerboard to match an infinite collision plane The infinite collision plane only specifies orientation, so we
Parameters
model : the collision plane
id : the id retured from creating the checkerboard
Definition at line 232 of file DrawList.h.
{
     // Mat4<T> H = sxformToHomogeneous(model.getLocation());
     _kinematicXform.at(id) = spatialTransformToQT(model.getLocation());
   }
References _kinematicXform, and spatialTransformToQT().
updateDebugSphereLocation()
template<typename T > void DrawList::updateDebugSphereLocation (Vec3< T > & position, size_t id) inline
Definition at line 247 of file DrawList.h.
{
     QMatrix4x4 H;
     H.setToIdentity();
     H.translate(position[0], position[1], position[2]);
     _kinematicXform.at(id) = H;
   }
References _kinematicXform.
updateRobotFromModel()
template<typename T > void DrawList::updateRobotFromModel (DynamicsSimulator< T > & model, size_t id, bool updateOrigin = false) inline
Update the position of a robot's bodies using the result of a dynamics simulation. Doesn't run the simulator - just pulls _Xa from the DynamicsSimulator
Parameters
model : the simulator
id : the id returned from the loadCheetah3 or loadMiniCheetah function.
Definition at line 180 of file DrawList.h.
{
     for (size_t modelID = 5, graphicsID = id; modelID < model.getNumBodies();
          modelID++, graphicsID++) {
       _kinematicXform.at(graphicsID) =
           spatialTransformToQT(model.getModel()._Xa.at(modelID));
     }
     if (updateOrigin) {
       _cameraOrigin = model.getState().bodyPosition.template cast<T>();
     }
   }
References _cameraOrigin, _kinematicXform, DynamicsSimulator< T >::getModel(), DynamicsSimulator< T >::getNumBodies(), DynamicsSimulator< T >::getState(), and spatialTransformToQT().
Member Data Documentation
_additionalInfoFirstVisit
bool DrawList::_additionalInfoFirstVisit = true private
Definition at line 314 of file DrawList.h.
_baseFileName
std::string DrawList::_baseFileName = "../resources/" private
Definition at line 299 of file DrawList.h.
_box_list
std::vector<BoxInfo> DrawList::_box_list private
Definition at line 320 of file DrawList.h.
_cameraOrigin
Vec3<double> DrawList::_cameraOrigin private
Definition at line 327 of file DrawList.h.
_canBeHidden
std::vector<u8> DrawList::_canBeHidden private
Definition at line 296 of file DrawList.h.
_cheetah3LoadIndex
size_t DrawList::_cheetah3LoadIndex = 0 private
Definition at line 329 of file DrawList.h.
_colorData
std::vector<std::vector<float> > DrawList::_colorData private
Definition at line 295 of file DrawList.h.
_cp_force
std::vector<std::vector<double> > DrawList::_cp_force private
Definition at line 319 of file DrawList.h.
_cp_pos
std::vector<std::vector<double> > DrawList::_cp_pos private
Definition at line 318 of file DrawList.h.
_cp_touch
std::vector<bool> DrawList::_cp_touch private
Definition at line 317 of file DrawList.h.
_cubeLoadIndex
size_t DrawList::_cubeLoadIndex = 0 private
Definition at line 330 of file DrawList.h.
_glArrayOffsets
std::vector<size_t> DrawList::_glArrayOffsets private
Definition at line 303 of file DrawList.h.
_glArraySizes
std::vector<size_t> DrawList::_glArraySizes private
Definition at line 304 of file DrawList.h.
_glColorData
std::vector<float> DrawList::_glColorData private
Definition at line 308 of file DrawList.h.
_glNormalData
std::vector<float> DrawList::_glNormalData private
Definition at line 307 of file DrawList.h.
_glVertexData
std::vector<float> DrawList::_glVertexData private
Definition at line 306 of file DrawList.h.
_grid_size
double DrawList::_grid_size private
Definition at line 322 of file DrawList.h.
_height_map
DMat<double> DrawList::_height_map private
Definition at line 324 of file DrawList.h.
_height_map_left_corner
Vec3<double> DrawList::_height_map_left_corner private
Definition at line 323 of file DrawList.h.
_height_map_max
double DrawList::_height_map_max private
Definition at line 325 of file DrawList.h.
_height_map_min
double DrawList::_height_map_min private
Definition at line 325 of file DrawList.h.
_instanceColor
vectorAligned<SolidColor> DrawList::_instanceColor
Definition at line 288 of file DrawList.h.
_kinematicXform
std::vector<QMatrix4x4> DrawList::_kinematicXform
Definition at line 289 of file DrawList.h.
_miniCheetahLoadIndex
size_t DrawList::_miniCheetahLoadIndex = 0 private
Definition at line 329 of file DrawList.h.
_modelOffsets
std::vector<QMatrix4x4> DrawList::_modelOffsets private
Definition at line 311 of file DrawList.h.
_normalData
std::vector<std::vector<float> > DrawList::_normalData private
Definition at line 294 of file DrawList.h.
_nTotal
size_t DrawList::_nTotal = 0 private
Definition at line 292 of file DrawList.h.
_nTotalGC
size_t DrawList::_nTotalGC = 0 private
Definition at line 316 of file DrawList.h.
_nUnique
size_t DrawList::_nUnique = 0 private
Definition at line 292 of file DrawList.h.
_objectMap
std::vector<size_t> DrawList::_objectMap private
Definition at line 301 of file DrawList.h.
_offsetXforms
vectorAligned<Mat4<float> > DrawList::_offsetXforms private
Definition at line 298 of file DrawList.h.
_reloadNeeded
bool DrawList::_reloadNeeded = false private
Definition at line 313 of file DrawList.h.
_scrollIDs
std::vector<ScrollInfo> DrawList::_scrollIDs private
Definition at line 309 of file DrawList.h.
_sphereLoadIndex
size_t DrawList::_sphereLoadIndex = 0 private
Definition at line 330 of file DrawList.h.
_vertexData
std::vector<std::vector<float> > DrawList::_vertexData private
Definition at line 293 of file DrawList.h.
_visualizationData
VisualizationData* DrawList::_visualizationData
Definition at line 56 of file DrawList.h.
The documentation for this class was generated from the following files:
DrawList.h
DrawList.cpp