Cheetah Software: FootstepPlanner Class Reference
FootstepPlanner Class Reference
#include <GraphSearch.h>
Public Member Functions
FootstepPlanner (bool verbose)
void reset ()
void buildInputTrajectory (float duration, float dt, InputTrajectoryState x0, float omega)
void planFixedEvenGait (std::vector< ContactState > &gait, float gait_period)
std::vector< InputTrajectoryState > & getInitialTrajectory ()
void addCost (FootplanStateCost cost)
void addCost (FootplanTransitionCost cost)
FootplanGoal & getGoal ()
Public Attributes
DefaultGaits defaults
Private Attributes
bool _verbose
FootplanStats _stats
FootplanGoal _goal
std::vector< FootplanStateCost > _stateCosts
std::vector< FootplanTransitionCost > _transitionCosts
std::vector< InputTrajectoryState > _inputTrajectory
Detailed Description
Definition at line 77 of file GraphSearch.h.
Constructor & Destructor Documentation
FootstepPlanner()
FootstepPlanner::FootstepPlanner (bool verbose)
Definition at line 9 of file GraphSearch.cpp.
                                              : _verbose(verbose) {
   _stats.reset();
   defaults.trotting = {{true, false, false, true},
                        {false, true, true, false}};
   defaults.standing = {{true, true, true, true}};
 }
References _stats, defaults, FootplanStats::reset(), DefaultGaits::standing, and DefaultGaits::trotting.
Member Function Documentation
addCost() [1/2]
void FootstepPlanner::addCost (FootplanStateCost cost) inline
Definition at line 87 of file GraphSearch.h.
{
     _stateCosts.push_back(cost);
   }
References _stateCosts.
addCost() [2/2]
void FootstepPlanner::addCost (FootplanTransitionCost cost) inline
Definition at line 91 of file GraphSearch.h.
{
     _transitionCosts.push_back(cost);
   }
References _transitionCosts.
buildInputTrajectory()
void FootstepPlanner::buildInputTrajectory (float duration, float dt, InputTrajectoryState x0, float omega)
Definition at line 22 of file GraphSearch.cpp.
{
   if(_verbose) {
     printf("Input trajectory with %d steps\n", (int)(duration / dt));
   }
   _inputTrajectory.clear();
   _inputTrajectory.reserve(duration / dt);
   Vec3<float> velocity(x0.v[0], x0.v[1], 0.f);
   Vec3<float> position(x0.p[0], x0.p[1], 0.f);
   float theta = x0.theta;
   float t = 0;
   for(uint32_t i = 0; i < (duration / dt); i++) {
     Vec3<float> vRot = ori::coordinateRotation(ori::CoordinateAxis::Z, theta).transpose() * velocity;
     _inputTrajectory.push_back({{position[0], position[1]}, {vRot[0], vRot[1]}, theta});
     position += vRot * dt;
     t += dt;
     theta += omega * dt;
   }
 }
References _inputTrajectory, _verbose, ori::coordinateRotation(), InputTrajectoryState::p, InputTrajectoryState::theta, InputTrajectoryState::v, and ori::Z.
getGoal()
FootplanGoal& FootstepPlanner::getGoal () inline
Definition at line 95 of file GraphSearch.h.
{
     return _goal;
   }
References _goal.
getInitialTrajectory()
std::vector<InputTrajectoryState>& FootstepPlanner::getInitialTrajectory () inline
Definition at line 83 of file GraphSearch.h.
{
     return _inputTrajectory;
   }
References _inputTrajectory.
planFixedEvenGait()
void FootstepPlanner::planFixedEvenGait (std::vector< ContactState > & gait, float gait_period)
Definition at line 44 of file GraphSearch.cpp.
{
   (void)gait;
   (void)gait_period;
 }
reset()
void FootstepPlanner::reset ()
Definition at line 16 of file GraphSearch.cpp.
{
   _stats.reset();
   _stateCosts.clear();
   _transitionCosts.clear();
 }
References _stateCosts, _stats, _transitionCosts, and FootplanStats::reset().
Member Data Documentation
_goal
FootplanGoal FootstepPlanner::_goal private
Definition at line 103 of file GraphSearch.h.
_inputTrajectory
std::vector<InputTrajectoryState> FootstepPlanner::_inputTrajectory private
Definition at line 107 of file GraphSearch.h.
_stateCosts
std::vector<FootplanStateCost> FootstepPlanner::_stateCosts private
Definition at line 105 of file GraphSearch.h.
_stats
FootplanStats FootstepPlanner::_stats private
Definition at line 102 of file GraphSearch.h.
_transitionCosts
std::vector<FootplanTransitionCost> FootstepPlanner::_transitionCosts private
Definition at line 106 of file GraphSearch.h.
_verbose
bool FootstepPlanner::_verbose private
Definition at line 101 of file GraphSearch.h.
defaults
DefaultGaits FootstepPlanner::defaults
Definition at line 99 of file GraphSearch.h.
The documentation for this class was generated from the following files:
GraphSearch.h
GraphSearch.cpp