Cheetah Software: test_filters.cpp File Reference
test_filters.cpp File Reference
Test filter functions.
#include "Dynamics/spatial.h"
#include "Math/FirstOrderIIRFilter.h"
#include "Math/orientation_tools.h"
#include "cppTypes.h"
#include "gmock/gmock.h"
#include "gtest/gtest.h"
Functions
TEST (Filters, firstOrderIIR)
Detailed Description
Test filter functions.
Test the various filters
Definition in file test_filters.cpp.
Function Documentation
TEST()
TEST (Filters , firstOrderIIR)
Test the firstOrderIIR filter with Eigen Vec3's
Definition at line 20 of file test_filters.cpp.
{
   Vec3<double> x0(1, 2, 3);
   FirstOrderIIRFilter<Vec3<double>, double> filt(0.2, x0);
   Vec3<double> update(5, 5, 5);
   filt.update(update);
   Vec3<double> expected = x0 * 0.8 + 0.2 * update;
   EXPECT_TRUE(almostEqual(expected, filt.get(), .0001));
 }
References almostEqual(), FirstOrderIIRFilter< T, T2 >::get(), and FirstOrderIIRFilter< T, T2 >::update().