Cheetah Software: SegfaultHandler.cpp File Reference
SegfaultHandler.cpp File Reference
Handler for segfaults. This will catch a segfault, print a stack trace, and put an error code in the shared memory (if it is connected), so that the simulator can provide a reasonable error message for why the robot code disappears.
#include <cstdio>
#include <execinfo.h>
#include <csignal>
#include <cstdlib>
#include <unistd.h>
#include <cstring>
#include "Utilities/SegfaultHandler.h"
#include "Utilities/Utilities_print.h"
Functions
static void segfault_handler (int sig)
static void sigint_handler (int sig)
void install_segfault_handler (char *error_message)
Variables
static char * error_message_buffer
Detailed Description
Handler for segfaults. This will catch a segfault, print a stack trace, and put an error code in the shared memory (if it is connected), so that the simulator can provide a reasonable error message for why the robot code disappears.
Definition in file SegfaultHandler.cpp.
Function Documentation
install_segfault_handler()
void install_segfault_handler (char * error_message)
Install the segfault handler function
Definition at line 53 of file SegfaultHandler.cpp.
{
   signal(SIGSEGV, segfault_handler);
   signal(SIGINT, sigint_handler);
   error_message_buffer = error_message;
 }
References error_message_buffer, segfault_handler(), and sigint_handler().
segfault_handler()
static void segfault_handler (int sig) static
Called on segfault. Prints stack trace, flushes output, and sends error code to sim
Parameters
sig : signal (should be SIGSEGV = 11)
Definition at line 28 of file SegfaultHandler.cpp.
{
   void* stack_frames[200];
   int size = backtrace(stack_frames, 200);
   fprintf_color(PrintColor::Red, stderr, "CRASH: Caught %d (%s)\n",
       sig, strsignal(sig));
   backtrace_symbols_fd(stack_frames, size, STDERR_FILENO);
   fflush(stderr);
   fflush(stdout);
   if(error_message_buffer)
     strcpy(error_message_buffer, "Segfault!\nCheck the robot controller output for more information.");
   exit(1);
 }
References error_message_buffer, fprintf_color(), and Red.
sigint_handler()
static void sigint_handler (int sig) static
Definition at line 43 of file SegfaultHandler.cpp.
{
   if(sig == SIGINT && error_message_buffer) {
     strcpy(error_message_buffer, "Robot program has been killed by SIGINT");
   }
   exit(0);
 }
References error_message_buffer.
Variable Documentation
error_message_buffer
char* error_message_buffer static
Definition at line 22 of file SegfaultHandler.cpp.