Cheetah Software: ControlParameterCollection Class Reference
ControlParameterCollection Class Reference
#include <ControlParameters.h>
Public Member Functions
ControlParameterCollection (const std::string &name)
void addParameter (ControlParameter *param, const std::string &name)
ControlParameter & lookup (const std::string &name)
std::string printToIniString ()
print all control parameters in the INI file format
std::string printToYamlString ()
bool checkIfAllSet ()
are all the control parameters initialized?
void clearAllSet ()
void deleteAll ()
Public Attributes
std::map< std::string, ControlParameter * > _map
Private Attributes
std::string _name
Detailed Description
ControlParameterCollections contains a map of all the control parameters.
Definition at line 77 of file ControlParameters.h.
Constructor & Destructor Documentation
ControlParameterCollection()
ControlParameterCollection::ControlParameterCollection (const std::string & name) inline explicit
Definition at line 79 of file ControlParameters.h.
 : _name(name) {}
Member Function Documentation
addParameter()
void ControlParameterCollection::addParameter (ControlParameter * param, const std::string & name) inline
Use this to add a parameter for the first time in the RobotControlParameters or SimulatorControlParameters. This should only be used during initialization of a ControlParameter.
Throws exception if you try to add a parameter twice.
Definition at line 88 of file ControlParameters.h.
{
     if (mapContains(_map, name)) {
       printf(
           "[ERROR] ControlParameterCollection %s: tried to add parameter %s "
           "twice!\n",
           _name.c_str(), name.c_str());
       throw std::runtime_error("Control parameter error [" + _name + "]: parameter " + name + " appears twice!");
     }
     _map[name] = param;
   }
References _map, _name, and mapContains().
checkIfAllSet()
bool ControlParameterCollection::checkIfAllSet ()
are all the control parameters initialized?
Check if all parameters have had their value set
Returns
if all set
Definition at line 78 of file ControlParameters.cpp.
{
   for (auto& kv : _map) {
     if (!kv.second->_set) {
       return false;
     }
   }
   return true;
 }
References _map.
clearAllSet()
void ControlParameterCollection::clearAllSet ()
Mark all parameters as not set
Definition at line 90 of file ControlParameters.cpp.
{
   for (auto& kv : _map) {
     kv.second->_set = false;
   }
 }
References _map.
deleteAll()
void ControlParameterCollection::deleteAll ()
Remove all parameters
Definition at line 99 of file ControlParameters.cpp.
{
   for(auto& kv : _map) {
     delete kv.second;
   }
   _map.clear();
 }
References _map.
lookup()
ControlParameter& ControlParameterCollection::lookup (const std::string & name) inline
Lookup a control parameter by its name. This does not modify the set field of the control parameter!
Throws exception if parameter isn't found
Definition at line 105 of file ControlParameters.h.
{
     if (mapContains(_map, name)) {
       return *_map[name];
     } else {
       throw std::runtime_error("Control parameter " + name +
                                " wasn't found in parameter collection " +
                                _name);
     }
   }
References _map, _name, and mapContains().
printToIniString()
std::string ControlParameterCollection::printToIniString ()
print all control parameters in the INI file format
Print all parameters to a string that can be used for an INI file
Definition at line 123 of file ControlParameters.cpp.
{
   std::string result = ";; Generated on " + getCurrentTimeAndDate() + "\n";
   // ini section
   result += "[";
   result += _name + "]\n\n";
   std::vector<std::string> lines;
   // names (and max name length)
   int maxLength_name = 0;
   for (auto& kv : _map) {
     maxLength_name = std::max(maxLength_name, (int)kv.first.length());
     lines.push_back(kv.first);
   }
   // pad, equals sign, and number
   size_t i = 0;
   int maxLength_number = 0;
   for (auto& kv : _map) {
     int charsToAdd = maxLength_name - (int)lines[i].length();
     assert(charsToAdd >= 0);
     for (int j = 0; j < charsToAdd; j++) {
       lines[i].push_back(' ');
     }
     lines[i] += " = ";
     lines[i] += kv.second->toString();
     maxLength_number = std::max(maxLength_number, (int)lines[i].length());
     i++;
   }
   // pad, ;;, and units
   i = 0;
   for (auto& kv : _map) {
     int charsToAdd = maxLength_number - (int)lines[i].length();
     assert(charsToAdd >= 0);
     for (int j = 0; j < charsToAdd; j++) {
       lines[i].push_back(' ');
     }
     lines[i] += " ;; ";
     if (kv.second->_units.empty()) {
       lines[i] += "No units specified.  Add them!";
     } else {
       lines[i] += kv.second->_units;
     }
     i++;
   }
   // combine lines
   for (auto& line : lines) {
     result += line + "\n";
   }
   return result;
 }
References _map, _name, and getCurrentTimeAndDate().
printToYamlString()
std::string ControlParameterCollection::printToYamlString ()
print all control parameters in the YAML file format
Print all parameters to a string which can be used as a YAML file
Definition at line 183 of file ControlParameters.cpp.
{
   std::string result = "# Generated on " + getCurrentTimeAndDate() + "\n";
   result += YAML_COLLECTION_NAME_KEY;
   result += ": ";
   result += _name + "\n\n";
   std::vector<std::string> lines;
   // names
   int maxLength_name = 0;
   for (auto& kv : _map) {
     maxLength_name = std::max(maxLength_name, (int)kv.first.length());
     lines.push_back(kv.first);
   }
   // name pad, :, and number
   size_t i = 0;
   int maxLength_number = 0;
   for (auto& kv : _map) {
     int charsToAdd = maxLength_name - (int)lines[i].length();
     assert(charsToAdd >= 0);
     for (int j = 0; j < charsToAdd; j++) {
       lines[i].push_back(' ');
     }
     lines[i] += ": ";
     lines[i] += kv.second->toString();
     maxLength_number = std::max(maxLength_number, (int)lines[i].length());
     i++;
   }
   // combine lines
   for (auto& line : lines) {
     result += line + "\n";
   }
   return result;
 }
References _map, _name, getCurrentTimeAndDate(), and YAML_COLLECTION_NAME_KEY.
Member Data Documentation
_map
std::map<std::string, ControlParameter*> ControlParameterCollection::_map
Definition at line 123 of file ControlParameters.h.
_name
std::string ControlParameterCollection::_name private
Definition at line 126 of file ControlParameters.h.
The documentation for this class was generated from the following files:
ControlParameters.h
ControlParameters.cpp