Cheetah Software: ControlParameterResponse Struct Reference
ControlParameterResponse Struct Reference
#include <ControlParameterInterface.h>
Public Member Functions
bool isResponseTo (ControlParameterRequest &request)
std::string toString ()
Public Attributes
char name [CONTROL_PARAMETER_MAXIMUM_NAME_LENGTH] = ""
u64 requestNumber = UINT64_MAX
u64 nParameters = 0
ControlParameterValue value
ControlParameterValueKind parameterKind
ControlParameterRequestKind requestKind
Detailed Description
Data sent from a control parameter collection in response to a request.
Definition at line 76 of file ControlParameterInterface.h.
Member Function Documentation
isResponseTo()
bool ControlParameterResponse::isResponseTo (ControlParameterRequest & request) inline
Check if a response is a valid response to a given request
Parameters
request : the request
Returns
is the response from the given request?
Definition at line 89 of file ControlParameterInterface.h.
{
     return requestNumber == request.requestNumber &&
            requestKind == request.requestKind &&
            std::string(name) == std::string(request.name);
   }
References ControlParameterRequest::name, name, ControlParameterRequest::requestKind, requestKind, ControlParameterRequest::requestNumber, and requestNumber.
toString()
std::string ControlParameterResponse::toString () inline
Convert to human-readable string
Returns
: description of the response
Definition at line 99 of file ControlParameterInterface.h.
{
     std::string result = "Response(" + std::to_string(requestNumber) + ") " +
                          controlParameterRequestKindToString(requestKind) +
                          " " +
                          controlParameterValueKindToString(parameterKind) +
                          " " + std::string(name) + " ";
     switch (requestKind) {
       case ControlParameterRequestKind::SET_USER_PARAM_BY_NAME:
         result += "user to: ";
         result += controlParameterValueToString(value, parameterKind);
         return result;
       case ControlParameterRequestKind::GET_USER_PARAM_BY_NAME:
         result += "user is: ";
         result += controlParameterValueToString(value, parameterKind);
         return result;
       case ControlParameterRequestKind::SET_ROBOT_PARAM_BY_NAME:
         result += "robot to: ";
         result += controlParameterValueToString(value, parameterKind);
         return result;
       case ControlParameterRequestKind::GET_ROBOT_PARAM_BY_NAME:
         result += "robot is: ";
         result += controlParameterValueToString(value, parameterKind);
         return result;
       default:
         return result + " unknown request type!";
     }
   }
References controlParameterRequestKindToString(), controlParameterValueKindToString(), controlParameterValueToString(), GET_ROBOT_PARAM_BY_NAME, GET_USER_PARAM_BY_NAME, name, parameterKind, requestKind, requestNumber, SET_ROBOT_PARAM_BY_NAME, SET_USER_PARAM_BY_NAME, and value.
Member Data Documentation
name
char ControlParameterResponse::name[CONTROL_PARAMETER_MAXIMUM_NAME_LENGTH] = ""
Definition at line 77 of file ControlParameterInterface.h.
nParameters
u64 ControlParameterResponse::nParameters = 0
Definition at line 79 of file ControlParameterInterface.h.
parameterKind
ControlParameterValueKind ControlParameterResponse::parameterKind
Definition at line 81 of file ControlParameterInterface.h.
requestKind
ControlParameterRequestKind ControlParameterResponse::requestKind
Definition at line 82 of file ControlParameterInterface.h.
requestNumber
u64 ControlParameterResponse::requestNumber = UINT64_MAX
Definition at line 78 of file ControlParameterInterface.h.
value
ControlParameterValue ControlParameterResponse::value
Definition at line 80 of file ControlParameterInterface.h.
The documentation for this struct was generated from the following file:
ControlParameterInterface.h