Cheetah Software: SimulatorSyncronizedMessage Struct Reference
SimulatorSyncronizedMessage Struct Reference
#include <SimulatorMessage.h>
Public Member Functions
void init ()
void waitForSimulator ()
void simulatorIsDone ()
void waitForRobot ()
bool tryWaitForRobot ()
bool waitForRobotWithTimeout ()
void robotIsDone ()
Private Attributes
SharedMemorySemaphore robotToSimSemaphore
SharedMemorySemaphore simToRobotSemaphore
Additional Inherited Members
Public Attributes inherited from SimulatorMessage
RobotToSimulatorMessage robotToSim
SimulatorToRobotMessage simToRobot
Detailed Description
A SimulatorSyncronizedMessage is stored in shared memory and is accessed by both the simulator and the robot The simulator and robot take turns have exclusive access to the entire message. The intended sequence is:
robot: waitForSimulator()
simulator: simulates robot (simulator can read/write, robot cannot do anything)
simulator: simDone()
simulator: waitForRobot()
robot: runs controller (robot can read/write, simulator cannot do anything)
robot: robotDone();
robot: waitForSimulator() ...
Definition at line 89 of file SimulatorMessage.h.
Member Function Documentation
init()
void SimulatorSyncronizedMessage::init () inline
The init() method should only be called after shared memory is connected! This initializes the shared memory semaphores used to keep things in sync
Definition at line 95 of file SimulatorMessage.h.
               {
     robotToSimSemaphore.init(0);
     simToRobotSemaphore.init(0);
   }
References SharedMemorySemaphore::init(), robotToSimSemaphore, and simToRobotSemaphore.
robotIsDone()
void SimulatorSyncronizedMessage::robotIsDone () inline
Signal that the robot is done
Definition at line 132 of file SimulatorMessage.h.
 { robotToSimSemaphore.increment(); }
References SharedMemorySemaphore::increment(), and robotToSimSemaphore.
simulatorIsDone()
void SimulatorSyncronizedMessage::simulatorIsDone () inline
Simulator signals that it is done
Definition at line 108 of file SimulatorMessage.h.
 { simToRobotSemaphore.increment(); }
References SharedMemorySemaphore::increment(), and simToRobotSemaphore.
tryWaitForRobot()
bool SimulatorSyncronizedMessage::tryWaitForRobot () inline
Check if the robot is done
Returns
if the robot is done
Definition at line 119 of file SimulatorMessage.h.
 { return robotToSimSemaphore.tryDecrement(); }
References robotToSimSemaphore, and SharedMemorySemaphore::tryDecrement().
waitForRobot()
void SimulatorSyncronizedMessage::waitForRobot () inline
Wait for the robot to finish
Definition at line 113 of file SimulatorMessage.h.
 { robotToSimSemaphore.decrement(); }
References SharedMemorySemaphore::decrement(), and robotToSimSemaphore.
waitForRobotWithTimeout()
bool SimulatorSyncronizedMessage::waitForRobotWithTimeout () inline
Wait for the robot to finish with a timeout
Returns
if we finished before timing out
Definition at line 125 of file SimulatorMessage.h.
{
     return robotToSimSemaphore.decrementTimeout(1, 0);
   }
References SharedMemorySemaphore::decrementTimeout(), and robotToSimSemaphore.
waitForSimulator()
void SimulatorSyncronizedMessage::waitForSimulator () inline
Wait for the simulator to respond
Definition at line 103 of file SimulatorMessage.h.
 { simToRobotSemaphore.decrement(); }
References SharedMemorySemaphore::decrement(), and simToRobotSemaphore.
Member Data Documentation
robotToSimSemaphore
SharedMemorySemaphore SimulatorSyncronizedMessage::robotToSimSemaphore private
Definition at line 135 of file SimulatorMessage.h.
simToRobotSemaphore
SharedMemorySemaphore SimulatorSyncronizedMessage::simToRobotSemaphore private
Definition at line 135 of file SimulatorMessage.h.
The documentation for this struct was generated from the following file:
SimulatorMessage.h